### ISSUE TITLE
v1.0.1 depend on linux/osx nuget libs even on Windows 10 .Net desktop

### ISSUE THREAD

**Issue by ps30** [ericsink/SQLitePCL.raw#102]
New depends require **.linux** and **.osx** nuget packages even when running on Windows 10 .Net only - see packages installed below.  Seems weird - how can I remove these packages under windows?

```
  <package id="sqlite-net-pcl" version="1.2.0" targetFramework="net462" />
  <package id="SQLitePCLRaw.bundle_green" version="1.0.1" targetFramework="net462" />
  <package id="SQLitePCLRaw.core" version="1.0.1" targetFramework="net462" />
  **<package id="SQLitePCLRaw.lib.e_sqlite3.linux" version="1.0.1" targetFramework="net462" />**
  **<package id="SQLitePCLRaw.lib.e_sqlite3.osx" version="1.0.1" targetFramework="net462" />**
  <package id="SQLitePCLRaw.lib.e_sqlite3.v110_xp" version="1.0.1" targetFramework="net462" />
  <package id="SQLitePCLRaw.provider.e_sqlite3.net45" version="1.0.1" targetFramework="net462" />
```

**Comment by ericsink** [comment]
Those dependencies are there

1.  So that 'net45' will be compatible with Mono on Linux and Mac.
2.  Because nuget can't do runtime-specific dependencies.  Yet.

When nuget gets this feature (I hear it's in progress), I should be able to tighten up those dependencies.

In the meantime, do note that the actual libs for Mac and Linux do not copied to your output directory.  The targets files check for that and do the right thing.

I seriously considered just building a "trio" package that contained all three, to make the extras less noticeable.  :-)
