### ISSUE TITLE
Question: Minimum API Level Android

### ISSUE THREAD

**Issue by jamesmontemagno** [ericsink/SQLitePCL.raw#103]
Just curious what the minimum API level supported is? via: https://github.com/Azure/azure-mobile-apps-net-client/issues/227

**Comment by ericsink** [comment]
I don't know for certain.  I would have to check and test it.  But I would expect that it's compatible a long way back.  Probably as far back as Xamarin.Android itself can go.  Like I said, this needs to be verified.

However, it's not clear in the azure-mobile-apps-net-client issue what source of compatibility is in play.  I assume their library may have API level restrictions that SQLitePCL.raw does not.  For example, if they don't support API level 14, it is probably not because of SQLitePCL.raw.

**Comment by jamesmontemagno** [comment]
Thanks @ericsink, yeah they could be using something odd under the hood I guess. From reading that they support 19+.

I was reading in your Readme about Android and SQLite failures with < 19 devices do to the version that it is on, so maybe it has to do with that.

**Comment by ericsink** [comment]
Ah, I see.

Compatibility is to some extent determined by which SQLite functions you are using and which instance of the SQLite library you are using.  So for example, if you are using a SQLite feature that was added in SQLite 3.7.14, then, well, you get the idea.

And if you are using the Android system SQLite, then this could be mapped on to the notion of Android API level compatibility by knowing which versions of Android shipped with which versions of SQLite.

That's the issue I mentioned in the README about sqlite3_close_v2().

And of course, this is different now that using the Android system SQLite is prohibited from Android N and up.

OTOH, if you are using a SQLite that is bundled with the app, then the question of Android API level compatibility becomes different.  It is in that context that I was thinking when I said that I believe SQLitePCL.raw is compatibility a long way back.

But the SQLite features you are calling are still determined by the specific build of SQLite you are using.

**Comment by jamesmontemagno** [comment]
Interesting, this all make sense. I actually am now looking into this and the bug was report against the old version, but their 3.0 is now using bundle_green, so it should be good.
