### ISSUE TITLE
Unable to use the new "SQLitePCL.raw.sqlite3_config()" to set threading mode

### ISSUE THREAD

**Issue by ggirard07** [ericsink/SQLitePCL.raw#106]
**Steps to reproduce**
1. Create a new solution with a PCL project (in my case profile 259).
2. Add a platform specific project with a dependency to the PCL (in my case Android).
3. Add necessary packages to those projects to use the bundle green edition.
4. From the PCL code, configure SQLite in serialized mode:

```
SQLitePCL.Batteries.Init();
var result = SQLitePCL.raw.sqlite3_config(SQLitePCL.raw.SQLITE_CONFIG_SERIALIZED);
if (result != SQLitePCL.raw.SQLITE_OK)
{
    System.Diagnostics.Debug.WriteLine($"Unable to set SQLIte in Serialized mode (error code = {result})");
}
```

**Expected result**
As I am understanding that bundles and providers are used to inject platform specific bits from the PCL by using bait/switch, this should be considered a possible case.

**Actual result**
Config call is failing and returning a SQLITE_MISUSE error.

**Remarks**
SQLite serialized mode cannot be set after `SQLitePCL.Batteries.Init()` or `SQLitePCL.raw.SetProvider()` as this last call try to open then close the DB which internally init the SQLite library. Once SQLite has been initialized, this is no longer permitted to use config to set the threading mode and result in a misuse error.
Even by doing so at the platform level, `SQLitePCL.raw.sqlite3_config()` still requires to call Init or SetProvider first, which prevent usage.

I am not sufficiently experienced with SQLite and your libraries to determine if there is an other way to validate the lib injection other than by opening/closing it...

**Comment by MKuckert** [comment]
I ran into the same problem. The problem is, that `SetProvider` opens a memory database which lets SQLite to initializing.

But there are two (pretty ugly) workarounds for the current implementation. I don't recommend to use them, but both document the underlying problem pretty good I think. I haven't fully tried them in an app, just played around in a Xamarin workbook.

### First: Create provider using reflection
var providerAssemblies = AppDomain.CurrentDomain.GetAssemblies().Where(asm => asm.FullName.StartsWith("SQLitePCLRaw.provider."));
if(!providerAssemblies.Any()) {
	// May happen, if the assembly is not loaded yet. Happens for example in Xamarin workbooks. Bad luck!
	throw new Exception("No SQLite provider found!");
}

// Find provider implementation
var providers = providerAssemblies.First().DefinedTypes.Where(t => typeof(ISQLite3Provider).IsAssignableFrom(t));
var provider = (ISQLite3Provider)Activator.CreateInstance(providers.First());

// Apply configuration
var configured = provider.sqlite3_config(raw.SQLITE_CONFIG_SERIALIZED);
if(configured==raw.SQLITE_OK) {
	// Successfully configured!
}
else {
	// Unable to configure SQLite3 provider
}

// Set provider
raw.SetProvider(provider);
```
This solution requires to not call `Batteries.Init` - and is so not very usable in conjunction with `sqlite-net-pcl`

### Second: shutdown and re-init
```csharp
Batteries.Init();

raw.sqlite3_shutdown();
var configured = provider.sqlite3_config(raw.SQLITE_CONFIG_SERIALIZED);
if(configured==raw.SQLITE_OK) {
	// Successfully configured!
}
else {
	// Unable to configure SQLite3 provider
}
raw.sqlite3_initialize();
```

**Comment by ericsink** [comment]
I *think* the fix here is to simply have SetProvider() stop checking to see if the provider actually works.

I only did this to help make errors occur earlier, but it is not necessary, and I don't think anything is depending on the current behavior.

**Comment by bordoley** [comment]
Unrelated to whether this should work, I'm curious why you are electing to use SQLite's serialized thread mode, as opposed to doing explicit locking in your application, or using a higher level library that guarantees thread safety?

A given SQLite connection isn't really meant to be used from multiple threads at the same time, hence the thread safe mode adds locks to all api calls. In this mode you need to be careful not to make SQLite calls from the mainloop of your application (assuming this is a mobile app), to avoid blocking the UI. To avoid this issue, Akavache, SQLite-net, and SQLitePCL.pretty all use variants of an internal scheduler to queue and schedule work for a given SQLite DB connection, dispatched to a task pool thread.

**Comment by ggirard07** [comment]
@MKuckert 

- For your first solution, I am not sure your solution is going to work on iOS, especially I am not sure the provider will be contained in the `AppDomain.CurrentDomain.GetAssemblies()` at runtime in a release build. MvvmCross faced this kind of issue for plugins IoC where they had to implement a kind of "bootstrap" to bypass `AppDomain` and reflection. Also, this defeat the `Batteries.Init` purpose.

- For the second case, nice to see there is a `sqlite3_shutdown` function I wasn't aware of. I am just wondering if this is considered a bad practice?
On iOS, SQLitePCL is relying on the native library bundled in the system. In that case, is the shutdown call applied at the system level, meaning shutdown is applied to every app? If true, is this also meaning that the threading mode configured with `sqlite3_config` is also shared by every apps, meaning any app on the device can shutdown the library, configure it to another serialization mode, then reinitialize it? This will defeat my whole usage of `sqlite3_config` if true :/

@ericsink It was my thought when I first had a look to the code but wasn't aware if you faced any situation where it was required. Is there any other funtion from the SQLite API that you can use in order to acheive the same aim but without initializing it? Like version or info related methods?

@bordoley this is because we were lazy and not experienced enough when we implemented SQLIite the first time in our apps. Since, we moved to the Async variant of the API in newer mobile apps which avoid the locking issue at the same time.
But for this precise case, we simply do not have time to refactor the code and more especially do not have time for retesting this part (I know... unit test is your best friend for this kind of scenario... but everything is a matter a time and resources...).
For now, the best, straightforward, solution was to keep the existing behavior which is working pretty fine in our case.

**Comment by ericsink** [comment]
There's another problem here.  On WinRT-ish platforms, the pinvoke provider calls sqlite3_win32_set_directory() in its constructor, and that ends up calling sqlite3_initialize().

**Comment by nathanielcook** [comment]
Looking at the SQLite [documentation](https://www.sqlite.org/threadsafe.html), which says "the default mode is serialized" (depending on compile time options), and looking at the compile options SQLitePCL.raw is using for [iOS](https://github.com/ericsink/SQLitePCL.raw/blob/master/apple/build-sqlite.sh) and [Android](https://github.com/ericsink/SQLitePCL.raw/blob/master/android/sqlite3/jni/Android.mk), it seems that we should be using Serialized by default, without having to call `sqlite3_config`. Am I wrong?

**Comment by ericsink** [comment]
You are correct.  The bundled e_sqlite3 builds are built with the default mode, serialized.

The need for `sqlite3_config` can arise when using some other SQLite library, such as the one from iOS.

**Comment by ericsink** [comment]
The pre-release of 1.1.1 (now on nuget.org) addresses this issue.

raw.SetProvider() no longer calls open/close, so sqlite3_initialize() should not end up getting called.

For WinRT-ish platforms, we still have the problem that the pinvoke provider constructor calls sqlite3_win32_set_directory(), and I can't remove those calls without breaking apps.  The workaround for that is to call sqlite3_shutdown(), then sqlite3_config(), then re-call sqlite3_win32_set_directory, which is now made available for that purpose.

**Comment by ericsink** [comment]
1.1.1 is now on nuget.org

**Comment by EnglishDave** [comment]
First, I want to clarify the reason this is occurring.  

The SQLite documentation states that "The sqlite3_config() interface may only be invoked prior to library initialization using sqlite3_initialize() or after shutdown by sqlite3_shutdown()." ([https://sqlite.org/c3ref/config.html](url)). Therefore, any action that results in sqlite3_config() being called, such as a call to SQLitePCL.Batteries.Init(), will mean that ANY call to 
sqlite3_config()  will fail and result in am SQLITE_MISUSE error code being returned. 

So as Martin Kuckert points out there are two solutions,  either (i) roll out your own SetProvider implementation which injects the platform specific ISqlite3Provider, performs any relevant calls to sqlite3_config(), and then calls sqlite3_initialize(); or (ii) call sqlite3_shutdown(), then any relevant calls to sqlite3_config(), and then calls sqlite3_initialize(). Option ii is probably the easiest to implement, however an important factor note is that sqlite3_config() is not Threadsafe and there must not be any open connections to any of the databases using the library being configured, so it must be used carefully (preferably just after SQLitePCL.Batteries.Init() is called, however theoretically you could dynamically change the library configuration if you can fully manage the connections and the threads on which it is done (not sure why you would want to though)). 

One additonal restriction to note id that if the SQLite library was compiled with SQLITE_CONFIG_SINGLETHREAD, you can not alter the configuration to use SQLITE_CONFIG_MULTITHREAD or SQLITE_CONFIG_SERIALIZED (you can determine this using a call to sqlite3_threadsafe() );

If you want to use SQLITE_CONFIG_SERIALIZED (presumably because databases will be accessed concurrently via multiple threads) you may want to consider improving performance by enabling Shared Pager Cache using sqlite3_enable_shared_cache(int) or opening connections with the  SQLITE_OPEN_SHAREDCACHE flag.

@ericsink, you mention that the bundled e_sqlite3 builds are built with the default mode, serialized, however if I run sqlite3_threadsafe() on iOS I get SQLITE_CONFIG_MULTITHREAD returned.

**Comment by ericsink** [comment]
@EnglishDave OK, but just to clarify, as of 1.1.1, released today, SetProvider() no longer indirectly calls  sqlite3_initialize(), so Batteries.Init() does not either.

**Comment by nathanielcook** [comment]
@EnglishDave make sure you're using a bundled SQLite and not the one built into iOS. Run a `select sqlite_version()` and make sure you get a newer version than the one built into your iOS version e.g. `3.14.1`. I'm using v1.1.0 of SQLitePCLRaw.

```
var result = SQLitePCL.raw.sqlite3_threadsafe();

string description = "";

switch (result)
{
    case 1:
        // Thread-safe. Lock statements not required.
        description = "Serialized";
        break;
    case 2:
        // Mutexing code is there, but mutexing on database connection and prepared statement objects is disabled.
        // Application is responsible for serializing access to database connections and prepared statements, so must use lock statements.
        description = "Multi-Threaded";
        break;
    default:
        // SQLite was compiled with mutexing code omitted. It is not safe to use SQLite concurrently from more than one thread.
        description = "Mutexing code omitted";
        break;
}

Logger.Debug("Threadsafe setting is: " + description);
```

The output from the above for me using bundle_e_sqlite3 on iOS is 
```
Threadsafe setting is: Serialized
```

**Comment by ggirard07** [comment]
Have a look at [the repo readme here](https://github.com/ericsink/SQLitePCL.raw#tldr).
NuGet package name seems to be `SQLitePCLRaw.bundle_e_sqlite3` (old package, `SQLitePCL.raw`, is documented as deprecated on NuGet)

**Comment by alicint** [comment]
ok thanks. now I'm using sqlite-net-pcl nuget package, How do I set the SQLiteConnection mode to Serialized using this library?

**Comment by ggirard07** [comment]
@alicint This repo is for SQLitePCL.raw only.

If you have questions about a package coming from another project, then consider using Stackoverflow instead.
If you want to report a bug against a package, then report an issue in the GitHub project associated to that package (https://github.com/praeclarum/sqlite-net for `sqlite-net-pcl` if I am right).
