### ISSUE TITLE
Update sqlcipher downstream

### ISSUE THREAD

**Issue by borrrden** [ericsink/SQLitePCL.raw#138]
Google Play is now [rejecting the version of openssl that Couchbase sqlcipher uses](https://github.com/couchbaselabs/couchbase-lite-libcrypto/issues/3).  We are working on upgrading, but will need you to upgrade as well since the dependency graph goes like this at the moment:

CBL -> SQLitePCL.raw -> sqlcipher

**EDIT** I'll comment here again when the built binaries are ready (Note:  we are dropping iOS libcrypto but iOS doesn't use it anyway)

**Comment by ericsink** [comment]
I should be able to update my stuff shortly after I hear confirmation from you.

**Comment by borrrden** [comment]
Ok the builds are updated to 1.0.2j.  After 1.4 we will look into moving to 1.1 but the build system has changed and we don't have time to sort it out right now.

**Comment by ericsink** [comment]
Cool.

But I just realized-- you guys are still back on SQLitePCL.raw 0.9.x, right?

**Comment by borrrden** [comment]
Hahahaha good point...that's right. I might have to switch back to a custom provider for android.

**Comment by ericsink** [comment]
I should be able to get you a build. It might take a little archeology on my part.

The other bad news is that I'm traveling, and now I can't even start on this until maybe Thursday afternoon, more likely Friday. But I still don't think it will take long to get it done.

**Comment by ericsink** [comment]
OK.  I have created a branch called 'older' off the commit back in August where 0.9.3 happened.

And I have added one commit to that branch which simply updates the submodule pointer and changes the version number (to 0.9.5, since there was a 0.9.4-pre, but never a 0.9.4).

That branch doesn't completely build successfully on my current tooling, since Xamarin doesn't support iOS Classic anymore.  But the sqlcipher stuff seems to build fine.

So, how should we proceed?  I am inclined to:

1.  Push *only* the nuget packages you need to be updated (instead of pushing up a whole new 0.9.5 release of all the packages).  Is it sufficient to just update SQLitePCL.plugin.sqlcipher.android ?

2.  Push them only after you have a chance to verify that they look okay.

**Comment by borrrden** [comment]
2 would probably be safer and waste less time for you.  Also yes I only need a build for Android, the others can stay the way they are.

**Comment by ericsink** [comment]
I think this got resolved, so I'm closing it.  Feel free to reopen if needed.
