### ISSUE TITLE
sqlite3_blob_open cannot be used in an optimized fashion

### ISSUE THREAD

**Issue by Therzok** [ericsink/SQLitePCL.raw#183]
In most cases, `sqlite3_blob_open` is called with the same arguments. On a specific use-case, the amount of memory allocated by sqlite3_blob_open reaches 64MB just by allocating byte arrays for the string parameters this function needs.

A possible workaround for this would be to provide helper methods in raw that take `byte[]` as parameter instead of string. Would this be plausible to implement via raw -> provider -> implementations?

https://github.com/dotnet/roslyn/issues/23424

**Comment by ericsink** [comment]
Interesting.

I can see how it would be helpful to expose an API that allows the conversion from string to byte[] to be skipped if it is already done.

But even if breaking compatibility were ignored, I doubt we want functions that accept utf8 to be the only API, as most apps will want SQLitePCL.raw to take responsibility for the string->utf8 conversion.

Thinking about this makes me wonder if it would be possible to keep the API the same and just cache the utf8 byte arrays.

I also notice that sqlite3_blob_open is not the only function with this problem.  There are lots of other instances where every call will allocate a byte[] array to convert a string to utf8.

**Comment by ericsink** [comment]
I added an overload for `sqlite3_blob_open` that I *think* would address the need here.

**Comment by ericsink** [comment]
SQLitePCL.raw pre-release version 1.1.10-pre20180223200113 has been pushed to nuget.  Testing feedback on the new overload would be appreciated.

**Comment by Therzok** [comment]
One of the problems with the overload is that the users of the API need to provide their own marshalling implementation (Util.ToUtf8 is internal).

Could that API be opened up?

**Comment by ericsink** [comment]
This request (making `util.to_utf8` public) initially struck me as odd.  (Why would they want that?  I thought the point was to avoid the allocation?)

But I think I see the point:  You have a string, and it still needs to be converted to utf8, but you only want to do that conversion (and its memory allocations) once.

However, I'm not sure SQLitePCL.raw should be including string->utf8 conversion routines part of its public API,. especially since my `util.to_utf8` is just a wrapper around `System.Text.Encoding.UTF8` stuff.

So, at the risk of being difficult, my first response here is to say, "I don't think I wanna do that.  You should probably just call `UTF8.GetBytes()` yourself.  Feel free to copy and paste my implementation if you like it."

But this isn't a hill I would die on.

**Comment by Therzok** [comment]
Yeah, it's not a blocker! This is good enough.

> especially since my util.to_utf8 is just a wrapper around System.Text.Encoding.UTF8 stuff.

Ah, I thought it was a special-cased version of utf8 encoding. Then it's all good!

**Comment by CyrusNajmabadi** [comment]
So i looked into adopting this for roslyn as part of the discussion in https://github.com/dotnet/roslyn/issues/23424.  SPecifically, i wanted to move from calling: 

![image](https://user-images.githubusercontent.com/4564579/106350964-b2867880-628d-11eb-9f95-14433abba899.png)

to calling

![image](https://user-images.githubusercontent.com/4564579/106350997-f8dbd780-628d-11eb-9c0c-561bec22e4ac.png)

My thought process was that i would just cache the well known utf8z forms of sdb/table/col as those are all constants in my system.  However, it turned out i was unable to do this because these are all ref-structs.  As such, i can't actually store them anywhere as that isn't allowed.  

I'm a little at a loss how to proceed here, though i really hope we can come up with a solutoin as it would be nice to avoid all this memory marshalling all over the place! :)

**Comment by CyrusNajmabadi** [comment]
Actually, i may have an approach using unsafe.  But it's pretty hacky and unpleasant :(

**Comment by CyrusNajmabadi** [comment]
@ericsink  @Therzok See here for how i addressed thsi: https://github.com/dotnet/roslyn/pull/50841/commits/ce2bf1286308281efc66cdbaacf7f132e4a1719f

I'm not a fan of this solution as it requires 'unsafe'.  However, there were no otehr way i could see to actually create a utf8z on demand without allocing.  Also, i couldn't create and cache utf8z's up front because they are ref-structs.   So this was the best solution i could come up with.
