### ISSUE TITLE
SQLitePCLRaw.bundle_zetetic missing SQLitePCLRaw.provider.sqlcipher.dll

### ISSUE THREAD

**Issue by sjlombardo** [ericsink/SQLitePCL.raw#196]
Hello @ericsink - thanks for adding in the bundle_zetetic package last year. We've been working with it a bit recently, and I've been having a problem using it. After adding SQLitePCLRaw.bundle_zetetic via NuGet, calling SQLitePCL.Batteries_V2.Init() results in an exception saying that SQLitePCLRaw.provider.sqlcipher can't be found. That assembly is only provided as part of SQLitePCLRaw.bundle_sqlcipher, or the various platform-specific packages. Does it make sense to add that to the SQLitePCLRaw.bundle_zetetic Nuget package as well?

**Comment by ericsink** [comment]
What platform is this happening on?

Looking back at the bundle_zetetic stuff, and jogging my memory a bit, I'm pretty sure I only made this work for iOS and Android.  For this platforms, provider.sqlcipher (or its counterpart) is present.  But if you're trying this on, say, Windows, you would probably get the behavior you describe.

So yeah, more work to be done here.

**Comment by sjlombardo** [comment]
Hi @ericsink - Thanks for the quick response! That might explain it, as I’m seeing this on windows.

**Comment by ericsink** [comment]
So, what platforms should bundle_zetetic try to support?

**Comment by sjlombardo** [comment]
I think bundle_zetetic could mirror bundle_sqlcipher in terms of platform support, or perhaps extend it. We currently offer supported library packages for iOS, macOS, watchOS, Android Windows Phone 8/8.1, Windows Runtime 8.1 (incl. ARM), Windows 10 UAP, Windows x86 and x64 (i.e. net35, net40, net45, netstandard11 and netstandard20), and Linux x86 and x64.

**Comment by sjlombardo** [comment]
Hi @ericsink - thanks so much for making those changes to bundle_zetetic! I don't fully understand the way that the gen_build works, but would it be possible to add WinRT and Windows Phone to batteries_zetetic with the following? 
```
        items_csproj.Add(config_csproj.create_batteries("batteries_zetetic",  ver,"win8", "sqlcipher"));
        items_csproj.Add(config_csproj.create_batteries("batteries_zetetic",  ver,"win81", "sqlcipher"));
        items_csproj.Add(config_csproj.create_batteries("batteries_zetetic",  ver,"wpa81", "sqlcipher"));
```
Or, would that have some separate impact on the bundling of batteries_sqlcipher?

We're also happy to help support testing of this change.

**Comment by ericsink** [comment]
Yes, I believe I can add those platforms rather easily.  I just wasn't sure the Win8 stuff was worth the trouble at this point.

However, if I (perhaps unfairly) interpret your remarks to say that I am free to dump all testing burden for bundle_zetetic on you, then I have no qualms.  :-)

I will add all the platforms I can.  I hope to provide you with a nupkg for testing within a week or so.

Thanks!

**Comment by sjlombardo** [comment]
Hi @ericsink - that sounds great, looking forward to the nupkg. We can definitely take care of testing the results on our end - thanks for your flexibility in making these changes!

**Comment by ericsink** [comment]
My current plan is that bundle_zetetic will gain support for all Windows platforms except Windows Phone 8.0.

That means I'm adding Windows 8.0, Windows 8.1, and Windows Phone 8.1 (which are the three you mentioned in a comment above).

WP80 is a very weird case because it doesn't support pinvoke.  SQLitePCL.raw does have some very basic support for this, but only for e_sqlite3.  It is not generalized for any other native sqlite-ish libs.  Supporting zetetic in that case would be more work, and I'd like to avoid that work, because WP80 support is something I plan to deprecate, not enhance.  :-)

**Comment by sjlombardo** [comment]
That sounds perfect. Dropping WP80 shouldn't be a problem. We are also planning to deprecate that!

**Comment by ericsink** [comment]
SQLitePCL.raw pre-release version 1.1.10-pre20180223200113 has been pushed to nuget.  It includes all the changes I've been making for bundle_zetetic.

I want bundle_zetetic to work really well.  Please let me know of any problems you encounter.  Thanks!

**Comment by ericsink** [comment]
@sjlombardo Not be a pest, but I wanted to check in and see if you folks have any testing feedback on the 1.1.10 prerelease yet.  :-)

**Comment by sjlombardo** [comment]
Hey @ericsink - thanks so much for putting together the prerelease. We started testing with some of the windows platforms today, and so far things are looking good. We're going to start testing on the mobile platforms next, and I'll provide an update as soon as we have some results. Thanks again for making this available!

**Comment by ericsink** [comment]
@sjlombardo Checking in.  Feel free to let me know of any problems you find.

**Comment by sjlombardo** [comment]
Hi @ericsink - Just a quick update. Testing on Windows desktops, Android, macOS, and iOS (with one caveat) are all working well so far in initial testing. I do have a couple quick questions.

First, I've been testing so far using the prerelease sqlite-net-base package instead of sqlite-net-pcl. When using sqlite-net-pcl 1.4.118, bundle_zetetic doesn't seem to be getting swapped in for bundle_green, as described in the FAQ item (https://github.com/ericsink/SQLitePCL.raw/wiki/How-to-use-SQLCipher-with-SQLite-net). Should that swapping work with bundle_zetetic?

The other question is specific to iOS. I'm seeing a runtime exception when the application declares a dependency on bundle_zetetic and then calls calling Batteries_v2.Init():
```
System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.lib.sqlcipher, Version=1.1.10.53, Culture=neutral, PublicKeyToken=980f7eff3ce1003e' or one of its dependencies.
```
It does work just fine however, if we instead use explicit provider initialization:

```SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_internal());```

Because Batteries_v2.Init() seems to work without any issues on the other platforms, I was wondering if the latter is the correct way to do things on iOS, or there is another issue. 

On deck next are Windows 8.1, and Windows Phone 8.1.

**Comment by ericsink** [comment]
The bait-and-switch thing (in the FAQ item you mentioned) should work with bundle_zetetic, which is to say, it should work as well as it does with any other bundle, which is to say, not very well.  :-)  That FAQ item could use some revision.

I'll say it this way:  If you have a case where that bait-and-switch works with bundle_e_sqlite3 but not with bundle_zetetic, then you found a bug.  But it is rather unlikely that there is a related bug here which is specific to bundle_zetetic.  More likely is that you are experiencing quirks that you would encounter with bundle_e_sqlite3 as well, because that FAQ item makes things appear simpler than they are in practice.

**Comment by ericsink** [comment]
The iOS problem with `Batteries_V2.Init()` might be a bug in bundle_zetetic.  I'll take a closer look.

**Comment by sjlombardo** [comment]
Hi @ericsink - we've wrapped up testing on our end, and all the platforms are in good shape. The only issue we've run into is that issue with iOS, and I see you've committed a change related to that. Let me know if you'd like me to verify anything there.

**Comment by ericsink** [comment]
@sjlombardo  The 1.1.10 release is now on nuget.org.  I'll leave this issue open for now until I hear from you on the fix for that iOS issue.  If that one checks out, then hopefully bundle_zetetic is in good shape.  If not, I'll try another fix, and in the meantime, I think I saw you mention a workaround.

Thanks for your help with the testing.

**Comment by sjlombardo** [comment]
Hello @ericsink - I just tested on iOS with the 1.1.10 release, and it seems to have fixed the problem with Batteries_V2.Init(), so I think bundle_zetetic is in good working order now!

**Comment by ericsink** [comment]
Excellent.  Thanks again.
