### ISSUE TITLE
Error: NUTC303B:Internal Compiler Error

### ISSUE THREAD

**Issue by Tiddev** [ericsink/SQLitePCL.raw#211]
Hello
In UWP Project (PCL Project not .netstandard) in Release Mode and with the .Net Native tool chain.

Exception:
> Severity	Code	Description	Project	File	Line	Suppression State
Error		Error: NUTC303B:Internal Compiler Error: Method 'instance System.Int32 SQLitePCL.ISQLite3Provider.sqlite3_bind_blob(System.IntPtr, System.Int32, System.Byte[], System.Int32)' is missing implementation on type 'SQLitePCL.SQLite3Provider_e_sqlite3' from assembly 'SQLitePCLRaw.provider.e_sqlite3' while loading type 'SQLitePCL.SQLite3Provider_e_sqlite3'. while computing compilation roots.

Thanks

**Comment by ericsink** [comment]
What version of SQLitePCL.raw are you using?

Which package brought SQLitePCL.raw into your project?  What version of that package are you using?

**Comment by Tiddev** [comment]
SQLitePCLRaw.bundle_sqlcipher 1.1.10 (on uwp platform)
sqlite-net-pcl 1.4.118 (on pcl)

Note that it works properly in the Debug mode, but it has an error in the Release mode

**Comment by ericsink** [comment]
If you can construct a test project/solution that reproduces the problem, I can figure out what's going wrong.

For now, a couple of wild guesses:

If you are using bundle_sqlcipher, consider this packaging of sqlite-net-pcl:

https://www.nuget.org/packages/sqlite-net-base/1.5.166-beta

This will avoid difficulties arising from having bundle_green and bundle_sqlcipher in the same project.

**Comment by Tiddev** [comment]
This problem also exists for this .NETSTANDARD
[App.zip](https://github.com/ericsink/SQLitePCL.raw/files/1874606/App.zip)

**Comment by Tiddev** [comment]
update sqlite-net-pcl to 1.5.166-beta did not affect!

**Comment by ericsink** [comment]
Thanks for sending the sample project.

It turns out my wild guess was correct.  By changing from sqlite-net-pcl to sqlite-net-base (note the different package ID), the build works.

I unzipped your project, opened it in VS 2017, change to release mode, and built the UWP app.  I get the error from above.

Then I edit App20.csproj (the netstandard/PCL project file) and do this:

1.  Remove SQLitePCLRaw.bundle_green
2.  Remove SQLitePCLRaw.core
3.  Change sqlite-net-pcl to sqlite-net-base, at version 1.5.166-beta

Then back to Visual Studio and build the UWP app again.  Now it builds.

sqlite-net-base differs from sqlite-net-pcl by not including a SQLitePCLRaw bundle.  This means you will need to initialize it yourself.  Add the following line to each of your app projects at start:

    SQLitePCL.Batteries_V2.Init();

**Comment by ericsink** [comment]
In what way did it not work for you?  

Do you have an error message? Any diagnostic information? 

You reopened this issue. How do want it to go forward?

**Comment by Tiddev** [comment]
> Severity	Code	Description	Project	File	Line	Suppression State
Error		Error: NUTC303B:Internal Compiler Error: Method 'instance System.Int32 SQLitePCL.ISQLite3Provider.sqlite3_blob_open(System.IntPtr, System.Byte[], System.Byte[], System.Byte[], System.Int64, System.Int32, System.IntPtr&)' is missing implementation on type 'SQLitePCL.SQLite3Provider_e_sqlite3' from assembly 'SQLitePCLRaw.provider.e_sqlite3' while loading type 'SQLitePCL.SQLite3Provider_e_sqlite3'. while computing compilation roots

**Comment by Tiddev** [comment]
Sorry i took your time.
You are right.
I got it wrong (sqlite-net-pcl with sqlite-net-base).

Thanks.

**Comment by ericsink** [comment]
No worries. Glad it's working now.  Cheers.
