### ISSUE TITLE
Missing implementation on type 'SQLitePCL.SQLite3Provider_e_sqlite3'

### ISSUE THREAD

**Issue by wjvii** [ericsink/SQLitePCL.raw#229]
This appears to be very similar to #211 but this one has to do with sqlcipher. I am using SQLitePCLRaw.bundle_sqlcipher and I get the same message. Error: NUTC303B:Internal Compiler Error: Method 'instance System.Int32 SQLitePCL.ISQLite3Provider.sqlite3_bind_blob(System.IntPtr, System.Int32, System.Byte[], System.Int32)' is missing implementation on type 'SQLitePCL.SQLite3Provider_e_sqlite3' from assembly 'SQLitePCLRaw.provider.e_sqlite3' while loading type 'SQLitePCL.SQLite3Provider_e_sqlite3'. while computing compilation roots.

I tried the suggestion in #211 but that did not work in my case and I was wondering if there is some other package I should use. This issue only arises when compiling with the native toolchain. It compiles in debug or release with the native toolchain disabled.

I do have a sample app if that would be helpful.

Thank you advance for any advice.

Walter

**Comment by ericsink** [comment]
If you have a sample app to repro the problem, yes, I would like to see it.  Thanks.

**Comment by ericsink** [comment]
Hmmm.

I confirm that I can reproduce the problem with the sample app you sent.

But I am not yet sure what to *do* about it...

I'll dig deeper.

**Comment by wjvii** [comment]
Thank you very much for taking a look at this!

**Comment by wjvii** [comment]
Eric, any thoughts yet on how to resolve this or maybe an idea for a workaround?

**Comment by ericsink** [comment]
Sorry for the delay.  Crazy week.

According to the results of some Google searches, in previous times when this error message appeared, it was a bug in the .NET Native code generator.  I can't be sure that the same is true this time, but I suspect it, partly because it is happening on a case that might be a bit odd, an overloaded method in an interface, with the overloads sharing the same first N params (IIRC).

I would like to gather some more evidence to back up this theory.

After that, either I need to workaround the issue or get the the relevant team to address it.  The workaround would be problematic, because it would probably involve a compatibility-breaking change.

The ball remains in my court.

**Comment by wjvii** [comment]
Absolutely no worries. I definitely understand being too busy!

My many thanks for the update and please let me know if there is any way I can help.

I did, just for grins, try to compile after updating to 15.8.4 hoping it was a compiler/code generation issue and it was the same result as before.

With security being so important and this being the best way to get encryption support for SQLite in UWP maybe you could suggest to the appropriate team to put in a unit test in for this before future updates to the .NET Native. code generator.

**Comment by KasperinK** [comment]
Any further info on this? The problem still persists.

**Comment by ericsink** [comment]
Not yet, but I'm currently working on another release, and hoping to give this some attention as part of that cycle.

**Comment by ericsink** [comment]
I'm sorry I've allowed issue this to dangle in the wind.

Let's throw up a bat signal to @bricelam

Brice, I've got an issue here that I suspect is a bug in .NET Native, but I don't have enough evidence for an indictment, much less a conviction.

Nonetheless, it appears this is happening due to a call from EF Core, so it's possible the issue is (or should be) on your radar screen.

If you have other customers experiencing this problem, it looks like it would be at the intersection of UWP, sqlite, and blobs.  Have you by chance seen this?

Like I said, my guess is that the .NET Native toolchain is losing track of one of the overloads of `sqlite3_bind_blob`.  In part, this guess is based on googling and seeing that previous appearances of a similar error message did turn out to be bugs of that flavor.  Also, I don't see how this problem could occur any other way, but I'm trying to stay open minded on that.  :-)

**Comment by bricelam** [comment]
@divega Know anyone on the .NET Native team we can get to help us dig into this?

**Comment by divega** [comment]
@MichalStrehovsky has been super helpful in the past with .NET Native issues.

**Comment by ericsink** [comment]
Hmph.

That's good info.  Disturbing, but good.

Thanks.

**Comment by ericsink** [comment]
OK, apologies to everyone here -- I should have caught this much sooner.

The thing that should have been glaringly obvious from the beginning is that this is a sqlcipher project, so `SQLite3Provider_e_sqlite3` isn't supposed to be there at all.  So why are we getting an error message about it?

The library project in this solution is referencing Microsoft.AppCenter.Crashes, and *that* is bringing in sqlite-net, which is bringing in an old version of bundle_green, which is causing build problems because bundle_sqlcipher is there too.

The easiest workaround is to just remove Microsoft.AppCenter.Crashes.  The solution builds just fine without it.

**Comment by wjvii** [comment]
Eric, excellent news and short term we can do that. Longer term we would like to keep using AppCenter.Crashes along with encrypting our own SQLite databases so should we file an issue with the AppCenter SDK team and see if something can be done to make this compatible when used together? Any other ideas or suggestions?

**Comment by ericsink** [comment]
See Microsoft/AppCenter-SDK-DotNet#569

**Comment by deakjahn** [comment]
I don't know the difference between your various versions but the [docs for `Microsoft.Data.Sqlite.Core`](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases) prescribe your `SQLitePCLRaw.bundle_winsqlite3`. And this one is in conflict with AppCenter, resulting in this error message. If I use `SQLitePCLRaw.bundle_green` instead, it works (at least I didn't find any difference in functioning). You might be able to tell whether this is a viable alternative or not but if it is, the docs might need to be changed.

**Comment by bricelam** [comment]
@deakjahn Those docs were written by the team who creates winsqlite3.dll 😉 Of course they'd prescribe it...
