### ISSUE TITLE
Static linking issue with bundle_zetetic under Xamarin.iOS

### ISSUE THREAD

**Issue by sjlombardo** [ericsink/SQLitePCL.raw#235]
Hello @ericsink, we're in the midst of finalizing a major update for SQLCipher and we'd like to fully support bundle_zetetic as part of the release. However, we're running into a problem with the Xamarin.iOS linker. It is removing our embedded library, because it thinks it is unused. I believe this is the same problem you ran into previously with #99.  

We think the right approach to fix this would be to use the same technique used in ios_unified.static, i.e. by creating an explicit dependency via `embedded.Init()` so that the linker will do the right thing. However, the Batteries_V2.Init() that is brought in via batteries_zetetic doesn't include that call on iOS, because EMBEDDED_INIT is not defined. 

Our initial though was that adding `cfg.defines.Add("EMBEDDED_INIT");` to `create_internal_batteries_zetetic()` in [gen_build.cs on line 1108](https://github.com/ericsink/SQLitePCL.raw/blob/master/gen_build.cs#L1108) would fix that. Then we could simply implement an `embedded.Init()` within our native library package that would complete the dependency chain and cause the Xamarin.iOS linker to do the right thing.

Do you think this would be a good approach to resolve the problem, or would you have any other suggestion for a better way to go about this?

**Comment by ericsink** [comment]
My initial reaction is to say yes, your diagnosis and proposed fix seem correct to me.  I will probably want to look more closely at this to make sure.  Assuming we proceed along those lines, I can make this minor change and get it in the release I am working on now.

That said, one question:  Did this previously work and then it broke?  Or have we found something about bundle_zetetic that was never quite right?  I assume the latter.

**Comment by sjlombardo** [comment]
I believe this was something that was never quite right, but we didn't initially notice it. We had tested this fairly extensively prior to the 1.1.11 release, but at the time our test application included some legacy dependencies. This inadvertently caused the Xamarin.iOS linker to perform the static linking, so we didn't experience the problem at this time. 

Only recently, as we've been preparing for release, did we notice that a new standalone reference project (i.e. with none of the legacy dependencies) would not link properly. 

Thanks so much for considering this, it would be wonderful to see this change in the next release!

**Comment by ericsink** [comment]
So the problem with the approach described above is that I can't build the batteries assembly without your lib assembly.  Or something pretending to be same.

You are building an iOS assembly that contains the static libraries for SQLCipher, right?  I'm referring to this as the lib assembly.  (This is the one that is getting optimized away the iOS linker.)

The right way to prevent this linker problem is indeed to put in a useless method and call it from somewhere.  However, my batteries assembly is just one example of a place to call it.  And I'm not entirely sure it's the best choice.

I see two options:

1.  We would probably be able to make this work with a bait and switch approach.  In other words, I don't really need a copy of your assembly.  I just need an assembly with the same name, that contains embedded_init.cs so that I can build against it.  This "bait" assembly is only used when I build, and I won't ship it in any nuget package.

2.  You still need a method to fool the iOS linker, but you deal with it entirely separate from SQLitePCL.raw.  Name the method what you want, and tell your iOS customers how/when to add a call to it.  My Zetetic support stuff wouldn't know or care about it.

Option 1 saves a step for your customers, which you may see as preferable.  Option 2 involves less coordination with me, which you may see as preferable.  :-)

**Comment by sjlombardo** [comment]
Hello @ericsink - thanks for the response. Yes, we are building an iOS assembly that contains the static libraries for SQLCipher (the lib assembly). 

What do you think about us just building embedded_init.cs (i.e. the same `SQLitePCL.lib` namespace, `embedded` class, and `Init()` method into our assembly? 

In other words, we'll make our switch assembly look like the existing library's bait. It will exactly mirror the SQLitePCLRaw.lib.sqlcipher.dll included in the sqlitepclraw.lib.sqlcipher.ios_unified.static.1.1.110 package. Then you can leave everything on your side the same since you already have that assembly present to build against, only as as stub. With the addition of `cfg.defines.Add("EMBEDDED_INIT");` from 9dff9cb, we'd be able to substitute in our own implementation of that assembly. 

Do you think that would work to provide the best of both worlds, with minimal effort for users, and minimal coordination required?

**Comment by ericsink** [comment]
That seems fine with me.

And to be clear, your assembly's name will be `SQLitePCLRaw.lib.sqlcipher.dll` ?

**Comment by sjlombardo** [comment]
Yes, that should be fine, we'll rename things on our side to make it work. Thanks again!

**Comment by ericsink** [comment]
So now I have a suggestion.

So bundle_zetetic has its own special version of the batteries assembly.  But the only difference with that special version is the lack of `EMBEDDED_INIT`.  If batteries_zetetic needs `EMBEDDED_INIT`, then batteries_zetetic doesn't need to exist, because it's not a special case anymore.  I can just use batteries_sqlcipher in there.

That will mean that bundle_zetetic is identical to my bundle_sqlcipher (for any platform supported by both) except the dependency on my SQLitePCLRaw.lib.sqlcipher package is omitted.  The actual contents of those two bundle packages will be identical.  The only difference will be in the dependencies.

Anyway, that also means the following two lines are effectively the same as what bundle_zetetic (for iOS) will become:

    <PackageReference Include="SQLitePCLRaw.bundle_sqlcipher" Version="1.1.11" />
    <PackageReference Include="SQLitePCLRaw.lib.sqlcipher.ios_unified.static" Version="1.1.11" ExcludeAssets="All" />
 
Which means you *should* be able to use that for testing.

If you add just these two PackageReference tags to an iOS app, the build should fail with unresolved stuff.  If you then add a reference to your lib assembly, with `embedded_init.cs` included in it, things should work, and the linker problem (from the start of this issue thread) should not happen.

**Comment by ericsink** [comment]
Other than the fact that I predicted a build failure instead of a runtime failure for that first step, this looks good.

So in summary, unless you have or uncover other concerns, I will proceed, incorporating the changes discussed above in my 1.1.12 release (coming soon-ish).

**Comment by sjlombardo** [comment]
That is great to hear, thank you so much!

**Comment by ericsink** [comment]
Version 1.1.12 was (finally) pushed up to nuget.org this morning.

**Comment by sjlombardo** [comment]
Hi @ericsink - we just tested this out and it's looking good. Thanks for resolving this!
