### ISSUE TITLE
Encrypted database doesn't work after upgrading to .net core 2.1.5

### ISSUE THREAD

**Issue by CoRlfKrl** [ericsink/SQLitePCL.raw#236]
Code did work with .net core 2.1.4
After upgrading to **.net core 2.1.5**

if no database exists, an unencrypted database will be created
if an encrypted database exists, this error is reported 

```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 26: 'file is not a database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
``` 
using packages
```
<PackageReference Include="Microsoft.AspNetCore.All" Version="[2.1.5]" />
...
<PackageReference Include="SQLitePCLRaw.bundle_sqlcipher" Version="[1.1.11]" />
```
in a docker file using Microsoft Base Image
```
FROM microsoft/dotnet:2.1.5-aspnetcore-runtime-stretch-slim AS base
```

**Comment by ericsink** [comment]
I think the mystery here is how it worked before the upgrade.

You're bringing in Microsoft.AspNetCore.All, which brings in Microsoft.Data.Sqlite, which brings in SQLitePCLRaw.bundle_green.

And then you add SQLitePCLRaw.bundle_sqlcipher.

That's the problem.  You have two SQLitePCLRaw bundles.

Instead of Microsoft.Data.Sqlite, you need Microsoft.Data.Sqlite.Core, which is the same thing, but without the dependency on bundle_green.

That means you probably need to replace your reference to Microsoft.AspNetCore.All.

cc @bricelam

**Comment by bricelam** [comment]
We recommend doing this:
``` xml
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.5" />
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="1.1.11" ExcludeAssets="All" />
<PackageReference Include="SQLitePCLRaw.bundle_sqlcipher" Version="1.1.11" />
```

**Comment by bricelam** [comment]
Otherwise the version of `SQLitePCLRaw.batteries_v2.dll` that gets used is ...non-deterministic. 😁

**Comment by CoRlfKrl** [comment]
Thanks!
This fixed it.

**Comment by CoRlfKrl** [comment]
Thanks for your quick response !!!!!
