### ISSUE TITLE
iOS apps are terminated every time they enter the background if they share an encrypted database with an app extension.

### ISSUE THREAD

**Issue by AwsomeCode** [ericsink/SQLitePCL.raw#241]
The same issue is reported to [https://github.com/sqlcipher/sqlcipher/issues/255](https://github.com/sqlcipher/sqlcipher/issues/255)
New Package is also now released [https://github.com/sqlcipher/sqlcipher/releases/tag/v4.0.0](https://github.com/sqlcipher/sqlcipher/releases/tag/v4.0.0)

I am also facing this issue. If possible please fix this as soon as possible. Thanks.

**Comment by ericsink** [comment]
So it looks like all I need to do is update my unofficial sqlcipher builds to use their 4.0 code?

**Comment by AwsomeCode** [comment]
I hope so upgrading to 4.0 will fix this. 
Because this [Comment](https://github.com/sqlcipher/sqlcipher/issues/255#issuecomment-375099032) of Mar 22 is mentioning [changes](https://github.com/sqlcipher/sqlcipher/issues/255#issuecomment-359917869) will be rolled into the next full release of SQLCipher. 
So 4.0 is just release 13 day ago so it may be having [those](https://github.com/sqlcipher/sqlcipher/issues/255#issuecomment-359917869) changes.

**Comment by sjlombardo** [comment]
The changes required to support Shared Containers on iOS are available in SQLCipher 4.0. However, there are some very important caveats:

1. The settings required to deal with the Shared Container issue require executing PRAGMA statements that [leave part of the database header unencrypted](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_plaintext_header_size). The application becomes responsible for storing and managing the salt in this case.
2. SQLCipher 4 does not by default open 3.x databases. Just like with the update from SQLCipher version 2 - version 3 there are options for [backwards compatibility and migration via PRAGMA](https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283) that require minor application changes.
3. Applications that are using the most recent sqlite-net will not be able execute the required PRAGMAs for 1 or 2 because of the change that forces WAL mode [in the connection constructor](https://github.com/praeclarum/sqlite-net/issues/765). We have submitted [pull request ](https://github.com/praeclarum/sqlite-net/pull/775) to that issue but it has not been merged. With out a resolution for item 3 it will be impossible for sqlite-net users to configure their applications to use Shared Containers or upgrade existing databases to SQLCipher 4.

**Comment by ericsink** [comment]
Hmmm.  @sjlombardo  item (2) is interesting.

That makes me think twice about updating my unofficial builds to your 4.x code.  At the very least, a semver disciple would say I need to reflect the compatibility break in a major version number change (as you have).

@AwsomeCode While I drag my feet on this, you may want to consider getting official builds from Zetetic instead.

**Comment by ericsink** [comment]
SQLitePCLRaw 2.0 contained unofficial e_sqlcipher builds based on SQLCipher community 4.x.
