### ISSUE TITLE
Error Result = NonDBFile with SQLCipher 3 encryption enabled

### ISSUE THREAD

**Issue by EdwardRushDeveloper** [ericsink/SQLitePCL.raw#259]
I am using the current Release from Nuget **SQLitePCLRaw.bundle_sqlcipher 1.1.13**. However, when using DB Browser for SQLite with **SQLCipher 3** to create and populate the database, I get the **NonDBFile exception** after executing with the Pragama Key. I was using sqlite-net-sqlcipher 1.5.231 but was getting the same error. So, I created my own code to step through the process. What I found was this:
1. I set the Pragama and execute the command, this is successful.
3. When I then use the DB Handle from the open operation to execute a query directly,  I get the NonDBFile error

See sample below:
  IntPtr handle;

//i am explicitly referencing the database here for my testing.
 **EMMA.FINSM.SQLite.SQLite3.Open("/data/user/0/EMMA.FINSM/files/EMMALite.sqlite", out handle);**

  //set my pragma command that appears to be successful with a **Done** replay
  **var stmt = SQLite.SQLite3.Prepare2(handle, "pragma key = 'D26CC3C0'");**

 **var r = SQLite3.Step(stmt);**

  **SQLite.SQLite3.Finalize(stmt);**

**///this line fails with the NonDBFile Exception
  var statment = SQLite.SQLite3.Prepare2(handle, "SELECT * FROM AppSetting");**

//this is the operation that fails
 **_var r = Prepare2 (db, query, System.Text.UTF8Encoding.UTF8.GetByteCount (query), out stmt, IntPtr.Zero);_**

**As a note, when I remove the encryption from the Database through the DB Browser for SQLite, the database operations are SUCCESSFUL.** 

I have also used extension .db, .db3 and .sqlite

**Comment by ericsink** [comment]
This problem is often due to a build configuration problem wherein you end up with more than one sqlite library, so you think your code is talking to sqlcipher, but it's not.

You can ask sqlite for its version number, which will give you a clue which native library you're actually using:

    SELECT sqlite_version()

If this returns 3.26.x, you're not actually talking to sqlcipher.

Feel free to post more details about which projects and packages are being used.  You're looking for something that is bringing in both sqlcipher and (probably) e_sqlite3.

**Comment by EdwardRushDeveloper** [comment]
Thank you so much for your reply. I just emailed you from my account. Thanks again. I will look further.

**Comment by EdwardRushDeveloper** [comment]
Yes, when I run the Query from my DB Browser I pull - 

3.26.0
--

**Comment by sjlombardo** [comment]
@EdwardRushDeveloper A very reliable way to determine if your application is properly linked to SQLCipher is to execute [`PRAGMA cipher_version`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_version). Because that PRAGMA is only impelemented in SQLCipher, if you execute that on a standard SQLite library it won't return a result. When you execute it through a SQLCipher library it will return the version number and potentially other build information. Try calling that from your application.

**Comment by ericsink** [comment]
I don't know what DB Browser is.  I assume it is *not* somehow making use of SQLitePCL.raw.  

I further assume the real issue here is what happens when you use SQLitePCL.raw with your own code and whether it works or not.

Another tidbit to try:  look in your project output directory.  If you see e_sqlite3.dll or libe_sqlite3.so or libe_sqlite3.dylib anywhere, that is a sign that somehow e_sqlite3 slipped in somewhere when you are trying to use sqlcipher.

**Comment by ericsink** [comment]
@sjlombardo Good tip.  I need to remember that one...

**Comment by EdwardRushDeveloper** [comment]
Well the only packages I have included in the project at this time are the MVVMCross bare framework version 6.2.3. It is really bare at this point. My assumption is the tool that I am using to create the database. I will try the PRAMA cipher_version call.

**Comment by ericsink** [comment]
What I was looking for was specific details on what sqlite-related packages you are using.  You mentioned sqlite-net-sqlcipher, but it wasn't clear if you were still using that.  Any others?

**Comment by EdwardRushDeveloper** [comment]
No, I am not using any packages. However, you made me start thinking about how I am creating the Database. I am using a tool to create the database (DB Browser for SQLite). I am setting the pass key with this tool. I am then including the database with my deployment in my assets in Android - Xamarin. It fails connecting when a key has been assigned to the database. I am using SqlCipher 3 as the option when setting the encryption with this tool.  So, I truly am a novice in regard to the SQLite Cipher technology, and I am wondering if the tool being used has a conflict with the sqlite-net-pcl, and your package. So I am going to run a battery of tests, and create the database with the sqlite-net-pcl code, set the key with this tool and see what my results are. Thanks for all your input.

**Comment by ericsink** [comment]
You say you're not using ANY sqlite packages, but if that's true, then I don't understand.  How is your code talking to sqlite with no sqlite packages?

But then you said something else that sounds like you're using sqlite-net-pcl.  Are you using that package or not?

I think I can help figure this out, but I need to know exactly which packages you are using.  Can you maybe post the content of your cspro file(s)j?

**Comment by EdwardRushDeveloper** [comment]
Thanks for your reply. Yes I am using your lasted cipher package and Sqlite-net-SQLCipher by Krueger. So I could step through the code, i put the colde from Krueger’s package in my own class file, as well as a reference to your bundle SQLCipher package 1.1.13. I believe it may b the issue with using the desktop tool SQLite db browser to set the encryption. I create the database with this desktop tool and add it to my assets. When I set the encryption with the sql desktop browser, it fails on the mobile device. But if i leave the encryption off it works. After seeing your reply, I think the issue resides in the idea that db browser tool is not applying the encryption the same. So when I get in my office later today, I will run tests, create the Db on the device with Krueger’s package, and set the encryption there. I just need the database prepopluated with data that I want to have a layer of security to make it hard to get into if my db happened to get moved to an unsecured location on the android device. It is just a security measure that I have to have so my infrastructure team don’t have questions. If they thought that I had an unsecured database, even in a sandboxed area, they would be raising Cane.

**Comment by ericsink** [comment]
Closing old/stale issue.
