### ISSUE TITLE
Update SQLite to v3.28.0 (security update)

### ISSUE THREAD

**Issue by kapsiR** [ericsink/SQLitePCL.raw#267]
Please update SQLite to v3.28.0 due to an already disclosed security vulnerability:
https://www.talosintelligence.com/vulnerability_reports/TALOS-2019-0777 ([CVE-2019-5018](https://nvd.nist.gov/vuln/detail/CVE-2019-5018))

**Comment by ericsink** [comment]
Acknowledged.  Will do.

**Comment by bricelam** [comment]
I find these "vulnerabilities" a little silly:

> An attacker can send a malicious SQL command

...but why are you letting users send SQL commands at all?? That's already, by definition, a SQL injection vulnerability. 😏

**Comment by ericsink** [comment]
@bricelam Agreed.

**Comment by Filip01011010** [comment]
Any timeline for a NuGet package update?

**Comment by ericsink** [comment]
I'll get to it soon.  Thanks for the nag.

**Comment by ericsink** [comment]
SQLitePCLRaw 1.1.14, which includes e_sqlite3 builds based on SQLite 3.28.0, has been pushed to nuget.org.

Note:  It appears that sqlite3_trace() in 3.28.0 does not behave exactly as it did in 3.26.0.  I noticed this only because one of my unit tests started failing.

Note also that sqlite3_trace() and sqlite3_profile() were deprecated in 3.14.0, almost 3 years ago, so my unit tests shouldn't still be using them anyway.
