### ISSUE TITLE
Consider API's based on Span<char> and Span<byte>

### ISSUE THREAD

**Issue by LukePulverenti** [ericsink/SQLitePCL.raw#268]
Given yesterday's announcement of [ .NET Core performance improvements](https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-core-3-0/) based on Span<T> and Memory<T>, I felt it was a good time to consider how these API's could be utilized within SQLitePCL.raw.

I've made some changes on my personal fork here as a means of demonstrating:
https://github.com/LukePulverenti/SQLitePCL.raw

For now I've started with:

- Change collation signature to use ReadOnlySpan<char>
- Change blob signature to return ReadOnlySpan<byte>

There are many more areas where these types could be adopted. Is this a direction you're interested in taking the library? I can continue to share changes as I make them. 

I would have submitted this as a pull request, but as these are breaking api changes, I did not expect you would merge them. I'm also using .NET Standard 2.0 as the minimum supported baseline, which I imagine may eliminate some of your desired supported platforms.

**Comment by ericsink** [comment]
You may wish to peek at the v2 branch and see discussion of same in #255 

And if you do look there, you will still find no use of Span.  :-(

But I want to use span.  I'm planning to do so.  And v2 is where that will happen.

And BTW, v2 is already on .NET Standard 2.0 as the minimum.

**Comment by LukePulverenti** [comment]
That's great to hear. Personally, if it were up to me, I would base the library on these types and leave it up to the consumer to decide when to call ToArray() or ToString().

**Comment by ericsink** [comment]
Tempting.

But I suspect the resulting change to the API would be too much for people to swallow.

But let's gather some data.  Or actually, a datum.  Just one, for now:

@bricelam What do you think?  Too radical?

**Comment by LukePulverenti** [comment]
You can always offer extension methods based on strings and arrays for those who need them. I think it would receive widespread praise as a next generation .net library.

**Comment by bricelam** [comment]
Seems fine to me.

I've though hard about where Span could actually help and it seem pretty limited. Most of the copying waste is actually due to UTF8 conversions, not splicing.

**Comment by LukePulverenti** [comment]
Yea that's why I started with the collation function as that is a string comparison that is using utf8 conversion.

**Comment by bricelam** [comment]
But using Span doesn't save you any memory if it's just over a to/from UTF8 copy anyway...

**Comment by bricelam** [comment]
IMHO, `sqlite3_prepare` is the ideal candidate for Span. `pzTail` is just a splice of `zSql`. This would reduce memory allocation when preparing SQL with multiple statements.

**Comment by bricelam** [comment]
Another way to optimize memory end-to-end is to add UTF8String overloads that let the caller decide if and when to convert between `string` and UTF8. This would enable things like the following:

* Caching SQL as UTF8 so it only has to be converted once
* Streaming UTF8 to the client directly instead of going through `string` and back.

**Comment by ericsink** [comment]
Here's one thing that I'm now pretty sure is correct:

As of 2019, SQLitePCL.raw is currently doing its UTF8 conversions too low.

According to the comments, the reason I had ISQLite3Provider work in terms of string instead of "IntPtr to UTF8" is because the code to do UTF8 conversions wasn't supported on all platforms.  I don't remember the details of this, but I suspect the problem was Windows Phone 8.0.  And that no longer applies.

So I'm not certain yet exactly what to do about UTF8String and Span or when, but it does seem like the first step is to change ISQLite3Provider to use IntPtr instead, and move all the UTF8 conversion stuff up a layer.

To say it another way, looking down the road a bit, I *do* think I will want SQLitePCL.raw to support scenarios where the conversion to/from System.String never happens (like with UTF8String as @bricelam  mentions), and using System.String at my lowest layer is an obvious obstacle to that.

**Comment by ericsink** [comment]
FWIW, some Span-ification work has happened in the v2 branch.

In general, the only changes I've done so far are in the provider API (under the hood), not the 'raw' API (public facing).  But the groundwork is mostly there.

One possibly interesting thing is that, despite the title of this issue and suggestions from @LukePulverenti , I haven't found much use for Span<char>.  I'm using Span<byte> in quite a few places for UTF-8, but Span<char> doesn't seem that helpful.

I did Spanify `sqlite3_prepare` as @bricelam suggested above.

Some of this work isn't going to make much difference in perf, but there are some clear wins here.  The most notable is in the common case of converting utf8 to a string.  I think that code was routinely doing an extra copy that didn't need to happen.

**Comment by ericsink** [comment]
So the first preview release of 2.0 has been pushed to NuGet, and at this point, a lot of Span-i-ness has taken place.

But it's all built around representing a utf8 string as `ReadOnlySpan<byte>`, not `UTF8String`.  I couldn't find much info about the level of support for the latter.  It looks like it is going to be in .NET Core 3.0, and perhaps nowhere else?
