### ISSUE TITLE
Getting error Unauthorized access to /system/lib64/libsqlite.so when added for SQLItePCL.raw lib

### ISSUE THREAD

**Issue by BhushanKD** [ericsink/SQLitePCL.raw#277]
Detected problem with app native libraries. libmonosgen-64bit-2.0.so : unauthorized access to /system/lib64/libsqlite.so

**Comment by ericsink** [comment]
In general, you need to provide much more detail for anyone to be able to effectively help.

That said, it looks like your code is trying to access the system sqlite library on Android, which Google does not allow as of Android N.

**Comment by BhushanKD** [comment]
Thanks Erik for replying.. Here is more information:
I have the Couchbase.Lite version:1.1.0.17178 referred in my project, this uses SQLitePCL.Raw (0.8.0) and SQLitePCL.ugly internally. 
Till now we were having no issues using it on Android 4.4. But now when we migrated to Android 7, we are getting warning popup "Detected problem with app native libraries. libmonosgen-64bit-2.0.so : unauthorized access to /system/lib64/libsqlite.so" in the debug mode.
By upgrading Couchbase.Lite to higher versions it did not resolve the issue.
There are blogs which suggests to use Couchbase.Lite.Storage.CustomSQLite but that will not work as we have already referred and using many classes from Couchbase.Lite.
So could you please suggest any solution for this issue to be resolved.
Note: We are using Xamerin for Android development

**Comment by ericsink** [comment]
Oh, wow.  You're using very old versions of Couchbase Lite.

(1)  Google changed the rules and doesn't allow access to the system SQLite library anymore.  Nothing we can do about that.

(2)  You're probably going to need to update to a more recent version of Couchbase Lite, which doesn't use SQLitePCLRaw anymore.  I can't help with that, but somebody at Couchbase probably can.  My contact there back in the day was @borrrden

**Comment by BhushanKD** [comment]
Thanks Ericsink, Yes its pretty old, what I can see there no dependency mentioned in new NuGet package for SQLite. I will check if uninstalling older Couchbase.Lite and installing new will work or not, otherwise I have to connect to @barrrden as you suggested.

**Comment by borrrden** [comment]
You shouldn’t be using Couchbase.Lite.Storage.CustomSQLite *instead of* but in addition to Couchbase.Lite. This allows the SQLite library to use a custom built SQLite instead of the default system one. 

The steps to correctly use it were in the forum post you made but they are also [here](https://docs.couchbase.com/couchbase-lite/1.4/csharp.html). The instructions there are for SQLCipher but they are very similar for CustomSQLite. Now the other thing is that as I mentioned the entire 1.x line is out of service and 2.0 redid the API so you’d be wise to migrate your project very soon. This is no longer related to SQLiteRaw.

**Comment by BhushanKD** [comment]
@borrrden , You mean to say I **should** use  Couchbase.Lite.Storage.CustomSQLite instead of Couchbase.Lite.

**Comment by BhushanKD** [comment]
@borrrden  Yes we are planning to move everything to latest.
