### ISSUE TITLE
Could not load list of method overrides due to Method not found: int SQLitePCL.ISQLite3Provider.sqlite3_win32_set_directory(int,string)'

### ISSUE THREAD

**Issue by ThomasLoidolt** [ericsink/SQLitePCL.raw#294]
Since my last update to version 2.0.0 I didn't get the SQLitePCLRaw to run on Xamarin for Android.

At the point of SQLitePCL.Batteries_V2.Init() I got the exception as in the header meant.
Before I removed the SQLitePCLRaw.provider.e_sqlite3.android package because 2.0.0 isn't supported and I ran into the exception "Failed to resolve System.String SQLitePCL.raw::sqlite3_column_name(SQLitePCL.sqlite3_stmt,System.Int32)" if the sqlite-net-pcl calls the raw api.

"sqlite-net-pcl" 1.6.258-beta
"SQLitePCLRaw.bundle_green" 2.0.1
"SQLitePCLRaw.core" 2.0.1
"SQLitePCLRaw.lib.e_sqlite3" 2.0.1
"SQLitePCLRaw.lib.e_sqlite3.android" 2.0.1

**Comment by ericsink** [comment]
sqlite-net has not yet been updated for compatibility with SQLitePCLRaw 2.0.  If you're using sqlite-net, you need to stay with SQLitePCLRaw 1.1.14 for now.

**Comment by ThomasLoidolt** [comment]
and what's about the SQLitePCLRaw.provider.e_sqlite3.android package? Should there be version 2.0 in future?

**Comment by ericsink** [comment]
The SQLitePCLRaw.provider.e_sqlite3.android package does not exist in 2.0, but the same functionality is provided by other packages.

Since 2.0 reduces the number of packages, the easiest way to upgrade is to remove all the SQLitePCLRaw packages and then bring in one of the SQLitePCLRaw.bundle_ packages and allow it to transitively bring in its dependencies.  You will end up with different package ids, but the functionality is the same.

FWIW, this (and all nuget package operations) works best with PackageReference instead of packages.config.

**Comment by Raystorm7** [comment]
> The SQLitePCLRaw.provider.e_sqlite3.android package does not exist in 2.0, but the same functionality is provided by other packages.
> 
> Since 2.0 reduces the number of packages, the easiest way to upgrade is to remove all the SQLitePCLRaw packages and then bring in one of the SQLitePCLRaw.bundle_ packages and allow it to transitively bring in its dependencies. You will end up with different package ids, but the functionality is the same.
> 
> FWIW, this (and all nuget package operations) works best with PackageReference instead of packages.config.

Hi,
in my application I'm using microsoft.data.sqlite.core 5.0.5 that requires SQLitePCLRaw.core >= 2.0.4.
How can I make all things works?
If I update to microsoft.data.sqlite.core verision 5.0.5 the error
Could not load list of method overrides due to Method not found: int SQLitePCL.ISQLite3Provider.sqlite3_win32_set_directory(int,string)
is trigger.

I can't use the older version.

Thank you.

**Comment by kroggen** [comment]
If the `sqlite3_win32_set_directory()` function is only present on Windows, why this wrapper tries to get its pointer on other platforms?

Check [here](https://github.com/ericsink/SQLitePCL.raw/blob/master/src/SQLitePCLRaw.provider.dynamic_cdecl/Generated/provider_dynamic_cdecl.cs#L1616)

This makes it impossible to use the dynamic provider on Mac

Also, it should not fallback to another sqlite library if the one I am trying to load fails due to the above. In another words: the wrapper is loading another instance, not the one I am asking it to load

**Comment by ericsink** [comment]
Closing old/stale issue.
