### ISSUE TITLE
SQLitePCLRaw v2 breaks xunit tests

### ISSUE THREAD

**Issue by Crono1981** [ericsink/SQLitePCL.raw#308]
Hello,

I was having issues using v2 in xunit tests project. Instantiating a new instance of `SqliteConnection` instance always resulted in a `not found` vanilla `Exception`.

While trying to isolate the source of the problem, I created a repo with dummy test projects in them. One with xunit, obviously, but also one with nUnit, MSTest and a straight console runner. Much to my surprise, the code did run fine in every other test engines. Moreover, it also did run with xunit if the dotnet core runtime was used instead of .NET 4.x.

As it turns out (and thanks to Brad Wilson for his amazing support through this!), the issue might be related with how dependencies are resolved in that particular context - most specifically, **dependencies relying on unmanaged code**. So he came up with a solution involving a config change to shadow copy the `AppDomain` assemblies to a new location. That did fix the issue.

So even though there *is* a workaround and that it seems that this is a xunit issue and not a PCL issue, I believe you may be able to provide further insights on top of Brad's ideas about what changed from v1 to v2 of SQLitePCLRaw that suddently caused xunit-based tests to break.

Here's the conversion thread with Brad Wilson:

https://github.com/xunit/xunit/issues/2037

And here's the sample repo:

https://github.com/RosairePion/wonderland-csharp-sqlitepclraw

Thank you both for the fantastic work you do!

**Comment by ericsink** [comment]
shadowCopy = false is the same thing I do when using xunit for tests of SQLitePCLRaw itself.

As you discovered, this problem is specific to .NET Framework and is not an issue with .NET Core.  SQLitePCLRaw uses a variety of techniques to locate and load the native sqlite library, depending on the platform and what APIs are available.  The .NET Framework case is one of the trickier ones.

The overall amount of change in this area for v2 was very significant, including a new provider which finds the native library in a more dynamic way.  The dynamic provider is used for .NET Framework (and Mono, which is similar).  I actually wish I could use it in more places, as it is very flexible.  But yes, it is quite sensitive to the notion of where (in the directory/path sense) it can look in order to find the native code library.  And xunit's shadow copy thing is one case that doesn't work out well at all.  :-)

**Comment by Crono1981** [comment]
You had me at

`shadowCopy = false is the same thing I do when using xunit for tests of SQLitePCLRaw itself.`

Thank you, this is helpful. :D

**Comment by Crono1981** [comment]
Out of curiosity, in your tests, do you use the same xunit options for both dotnet core and .NET Framework?

I'm tempted to leave the configuration file out of the dotnet core tests. I like being as close to default settings as possible with the tools I use, makes it easier for somebody else to pick it up or to diagnose issues.

**Comment by ericsink** [comment]
I leave the xunit.runner.json file in place for all the tests.  I don't think the setting would have any effect with .NET Core.  

In fact, I'm just listing multiple TFMs in the cs proj file.  In this repo, take a peek at this directory:

/test_nupkgs/e_sqlite3/real_xunit

Now that you mention it, it probably would be more correct to put the ItemGroup for the xunit.runner.json copying conditional on TFM.  But like I said, it doesn't seem to matter.

**Comment by Crono1981** [comment]
> Now that you mention it, it probably would be more correct to put the ItemGroup for the xunit.runner.json copying conditional on TFM.

This is what I did. Felt better doing that rather than having xunit trying to guess what I'm trying to accomplish by changing a default setting it would normally disregard, now or in a future version.

Guess that's just me overthinking it. I do that a lot.

Again, thanks for sharing with me.

**Comment by ericsink** [comment]
The difference between a software developer and a computer scientist?  The software developer looks both ways before crossing a one-way street.
