### ISSUE TITLE
UWP Sqlite 'VACUUM; error

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#339]
Investigate dotnet/efcore#20253

**Comment by ericsink** [comment]
@fernand-delavy
@bricelam

I *think* the problem is that `sqlite3_win32_set_directory()` is never being called.

This was one of the breaking changes in SQLitePCLRaw 2.x:

https://github.com/ericsink/SQLitePCL.raw/blob/master/v2.md

I took the Test.zip file posted as part of the original issue, removed Microsoft.Data.Sqlite, added SQLitePCLRaw 2.0.2, and tweaked the code accordingly.  This reproduces the same error mentioned by the original issue.  Then I added `sqlite3_win32_set_directory()` calls, and the error goes away.

**Comment by Fernand-Delavy** [comment]
Hello Sir,

I'd appreciate it if you send back the modified Test App, thank you

Regards

Fernand Delavy
Rue Carlo Hemmerling 11
CH-1804 Corsier-sur-Vevey
Email :     fernand.delavy@outlook.com
Tél :          +41 21 922 85 65
Mobile :  +41 79 668 29 94

De : Eric Sink <notifications@github.com>
Envoyé : mercredi, 18 mars 2020 13:39
À : ericsink/SQLitePCL.raw <SQLitePCL.raw@noreply.github.com>
Cc : Fernand-Delavy <fernand.delavy@outlook.com>; Mention <mention@noreply.github.com>
Objet : Re: [ericsink/SQLitePCL.raw] UWP Sqlite 'VACUUM; error (#339)


@Fernand-Delavy<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFernand-Delavy&data=02%7C01%7C%7C97d983aa2efe4902c2a008d7cb395ee2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637201319564163180&sdata=Vk6gTXZrLQhV49og3wUVgzv7XoaD2cmr%2BhU1cKbTA14%3D&reserved=0>
@bricelam<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbricelam&data=02%7C01%7C%7C97d983aa2efe4902c2a008d7cb395ee2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637201319564173188&sdata=ykiUT5xqdnWa4cY5ajkLYcRTZ06OVqULFZlBzDE0il4%3D&reserved=0>

I think the problem is that sqlite3_win32_set_directory() is never being called.

This was one of the breaking changes in SQLitePCLRaw 2.x:

https://github.com/ericsink/SQLitePCL.raw/blob/master/v2.md<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fericsink%2FSQLitePCL.raw%2Fblob%2Fmaster%2Fv2.md&data=02%7C01%7C%7C97d983aa2efe4902c2a008d7cb395ee2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637201319564173188&sdata=u9FL6exRkrLvAKJZZyEpL9RfVOU1qflJfKhXFG7VX7M%3D&reserved=0>

I took the Test.zip file posted as part of the original issue, removed Microsoft.Data.Sqlite, added SQLitePCLRaw 2.0.2, and tweaked the code accordingly. This reproduces the same error mentioned by the original issue. Then I added sqlite3_win32_set_directory() calls, and the error goes away.

**Comment by ericsink** [comment]
[Test2.zip](https://github.com/ericsink/SQLitePCL.raw/files/4349353/Test2.zip)

**Comment by ericsink** [comment]
Closing old/stale issue.
