### ISSUE TITLE
Migrate packages.config -> PackageReference causes 'VTable setup of type SQLitePCL.SQLite3Provider_sqlite3 failed'

### ISSUE THREAD

**Issue by zoli13** [ericsink/SQLitePCL.raw#361]
After migrating 'packages.config' -> 'PackageReference' using VS2019, Xamarin forms project compiles fine, but I receive an error during iOS/Simulator startup at App.cs/Initialize()
`SQLitePCL.Batteries_V2.Init():` 
  ->
`System.TypeLoadException: 'VTable setup of type SQLitePCL.SQLite3Provider_sqlite3 failed'`

It happens only on iOS (I tried only in Simulator), the Android runs fine, no such error.

**Before migrate:**

packages.config:

    <package id="SQLiteNetExtensions" version="2.0.0" targetFramework="xamarinios10" />
    <package id="sqlite-net-pcl" version="1.4.118" targetFramework="xamarinios10" />
    <package id="SQLitePCLRaw.bundle_green" version="1.1.5" targetFramework="xamarinios10" />
    <package id="SQLitePCLRaw.bundle_sqlcipher" version="1.1.5" targetFramework="xamarinios10" />
    <package id="SQLitePCLRaw.core" version="1.1.10" targetFramework="xamarinios10" />
    <package id="SQLitePCLRaw.lib.sqlcipher.ios_unified.static" version="1.1.10" targetFramework="xamarinios10" />
    <package id="SQLitePCLRaw.provider.internal.ios_unified" version="1.1.10" targetFramework="xamarinios10" />
    <package id="SQLitePCLRaw.provider.sqlite3.ios_unified" version="1.1.5" targetFramework="xamarinios10" />

ios.csproj  

    <Reference Include="SQLite-net, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">      <HintPath>..\..\packages\sqlite-net-pcl.1.4.118\lib\netstandard1.1\SQLite-net.dll</HintPath>
    <Reference Include="SQLiteNetExtensions, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">      <HintPath>..\..\packages\SQLiteNetExtensions.2.0.0\lib\portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1\SQLiteNetExtensions.dll</HintPath>
    <Reference Include="SQLitePCLRaw.batteries_v2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8226ea5df37bcae9, processorArchitecture=MSIL">      <HintPath>..\..\packages\SQLitePCLRaw.bundle_sqlcipher.1.1.5\lib\Xamarin.iOS10\SQLitePCLRaw.batteries_v2.dll</HintPath>
    <Reference Include="SQLitePCLRaw.core, Version=1.1.10.86, Culture=neutral, PublicKeyToken=1488e028ca7ab535, processorArchitecture=MSIL">      <HintPath>..\..\packages\SQLitePCLRaw.core.1.1.10\lib\Xamarin.iOS10\SQLitePCLRaw.core.dll</HintPath>
    <Reference Include="SQLitePCLRaw.lib.sqlcipher">      <HintPath>..\..\packages\SQLitePCLRaw.lib.sqlcipher.ios_unified.static.1.1.10\lib\Xamarin.iOS10\SQLitePCLRaw.lib.sqlcipher.dll</HintPath>
    <Reference Include="SQLitePCLRaw.provider.internal">      <HintPath>..\..\packages\SQLitePCLRaw.provider.internal.ios_unified.1.1.10\lib\Xamarin.iOS10\SQLitePCLRaw.provider.internal.dll</HintPath>

**After migrate:**

ios.csproj

    <PackageReference Include="SQLiteNetExtensions">      <Version>2.0.0</Version>    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.bundle_sqlcipher">      <Version>1.1.5</Version>    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.lib.sqlcipher.ios_unified.static">      <Version>1.1.10</Version>    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.provider.internal.ios_unified">      <Version>1.1.10</Version>    </PackageReference>

The migrate dialog offered this by default, I accepted it:

![migrate](https://user-images.githubusercontent.com/9251057/91716240-886e4480-eb8f-11ea-9ad3-4fa7c8089c47.png)

Any idea what could cause this error?

**Comment by ericsink** [comment]
There are multiple problems here, and I'm not sure which of them might be causing the symptom you are seeing.

(1)  If you explicitly include `SQLitePCLRaw.bundle_sqlcipher`, you do need to explicitly include `SQLitePCLRaw.lib.sqlcipher.ios_unified.static` or `SQLitePCLRaw.provider.internal.ios_unified`.  They will come in as transitive dependencies, and doing it that way will keep them matched to the version `SQLitePCLRaw.bundle_sqlcipher`.

(2)  If you want to use SQLitePCLRaw 1.x (which is no longer actively maintained) instead of 2.x (which contains breaking changes),then I suggest you use version 1.1.14.

(3)  You have `bundle_sqlcipher` as well as `bundle_green`, but you should never have more than one `SQLitePCLRaw` bundle package.  It is a surprising that this ever worked.  It looks like what you want is `bundle_sqlcipher`, and that `bundle_green` is coming in transitively through `sqlite-net-pcl` which is coming in transitively through `SQLiteNetExtensions`.  The usual advice is to use `sqlite-net-base` (1.6.x, in your case) instead of `sqlite-net-pcl`.  But since `bundle_green` is coming in transitively, you probably need to do something like this to get rid of it:

```
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="1.1.14" ExcludeAssets="All" />
```

**Comment by zoli13** [comment]
Thank you.
Unfortunately we suspended this project for now, so I cannot test your suggestions.
One thing is sure, it works, regardless how crazy way packages are mixed.
So it does not seem to be an issue, but a user error - so I will close this ticket.
Later I can report back if we do the upgrade.
