### ISSUE TITLE
How to achieve manual "bundling"?

### ISSUE THREAD

**Issue by tinmanjk** [ericsink/SQLitePCL.raw#388]
Following the documentation:
_But the word "whatever" is different on each platform. For example, on Android, using e_sqlite3, you need:

    SQLitePCLRaw.core
    SQLitePCLRaw.provider.e_sqlite3.android
    SQLitePCLRaw.lib.e_sqlite3.android

and you need to call:

SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_e_sqlite3());_

I created a console application targeting 4.7.2 Framework.
I added the 3 nugget packages - core/provider/lib - provider and lib having identical names - so should be able to play together.

However I get this: ![image](https://user-images.githubusercontent.com/22401916/102574240-fb78d800-40f8-11eb-85ad-31c5a72e638a.png)

**Comment by ericsink** [comment]
You might want to explain why you want to do manual bundling instead of using the provided bundles.

The fact that the provider and lib have identical base names is not a sign that they should be able to play together.

The best way to figure out how to make a manual bundle for a given platform is to study how the provided bundles work and how they implement that platform.

And BTW, PackageReference is *so* much better than packages.config.  :-)

**Comment by ericsink** [comment]
Closing old/stale issue.
