### ISSUE TITLE
Different behaviour between e_sqlite and sqlite commandline for URLs

### ISSUE THREAD

**Issue by Therzok** [ericsink/SQLitePCL.raw#407]
Hey there,

When inserting sqlite into vsmac with a version that had the implementation previous to [this roslyn PR](https://github.com/dotnet/roslyn/pull/51682), we were getting `db already attached` errors`.

I've attached a minimal sample project which reproduces this issue:
https://gist.github.com/Therzok/eccb1781c2fd099c541eecec240c3301

The Query1, Query2, Query3 methods are the ones which execute an sqlite command with different variations. Query2 and Query3 are the peculiar ones, since the trailing slash makes the difference between `already attached` and `works`.

The code itself tries to create an in-memory write cache using different mechanisms. It seems that one of the cases is not handled correctly, and I'm not sure why, it only happens on macOS.

**Comment by Therzok** [comment]
The reason for this bug is that `sqlite3` REPL does not reproduce this issue when missing the trailing `/`, but sqlitepclraw does.

**Comment by ericsink** [comment]
Quick reply, I haven't looked at the repro gist in depth yet, but this may be related to the question of whether URI filenames are enabled in SQLite, which is documented here:

https://sqlite.org/uri.html

Except it's not obvious how that would explain this being OSX-specific.  That's still a mystery at this point.

Anyway, since you're highlighting a difference in behavior w.r.t. the sqlite3 REPL, I note that shell.c has this config call:

```
  sqlite3_config(SQLITE_CONFIG_URI, 1);
```

I'll take a closer look at the repro gist ASAP.

**Comment by CyrusNajmabadi** [comment]
I saw that @ericsink, however as per the docs we do this:

> Regardless of the compile-time or start-time settings, URI filenames can be enabled for individual database connections by including the SQLITE_OPEN_URI bit in the set of bits passed as the F parameter to sqlite3_open_v2(N,P,F,V). 

Even though we pass SQLITE_OPEN_URI we still have an issue here.

**Comment by ericsink** [comment]
I've got the repro gist building here, and of course, it works fine on Windows.  I don't have a Mac here at home.  I'll need to take a closer look at this tomorrow.  It's just hard to imagine why this is OSX-specific.  The e_sqlite3 builds are compiled exactly the same way on all platforms.

Still digging...

**Comment by ericsink** [comment]
OK, here is what I have found:

Over in my ericsink/cb repo, in the item407 directory, is a translation of your repro program to C.  You should see commits linked above where I tagged this issue.  The C repro allows the problem to be demonstrated without SQLitePCLRaw itself, with no .NET stuff involved.

Once I realized that, I suspected something was wrong with my `e_sqlite3` builds.  However, the problem also happens when linking the C repro against the system SQLite library on MacOS.  FWIW, my `e_sqlite3` builds are SQLite 3.34.0, and the system SQLite on my Mac shows 3.28.0.

So why does it happen in the repro program but not in the SQLite REPL?

Well actually it *does* happen in the SQLite REPL.

It turns out that if you remove the SQLITE_OPEN_SHAREDCACHE flag from the sqlite3_open_v2 call, then the problem doesn't appear.  I'm not claiming this is a suitable fix for your situation, just reporting the distinction.

From there, it seemed likely that the different with the SQLite REPL was that it was probably not opening the file in sharedcache mode.  It turns out that if you do open the file that way, the REPL will give the same error.

FWIW, the problem actually happens on Linux as well as on OSX, but not on Windows.

**Comment by ericsink** [comment]
```
Erics-Mac-mini:item407 eric$ sqlite3 'file:///Users/eric/dev/cb/item407/storage.ide/?mode=memory&cache=shared'
SQLite version 3.28.0 2019-04-15 14:49:49
Enter ".help" for usage hints.
sqlite> attach 'file:///Users/eric/dev/cb/item407/storage.ide/?mode=memory&cache=shared' as plok;
Error: database is already attached
sqlite> ^D
Erics-Mac-mini:item407 eric$ 
```

**Comment by Therzok** [comment]
Thank you so much for investigating this. Is there any way we can signal it upstream?

**Comment by ericsink** [comment]
By "upstream" do you mean "to the SQLite developers" ?

Perhaps the SQLite forum:

https://sqlite.org/forum/forum

DRH et al are quite helpful on questions like this.  As a starting point, they should be able to clarify whether the behavior is expected or if it is something they would consider as a bug.  It is possible this issue is already known, but I have not done exhaustive searches to try and find out.

**Comment by ericsink** [comment]
I was too curious so I went ahead and posted to the forum about this:

https://sqlite.org/forum/forumpost/9babfc9cba

**Comment by ericsink** [comment]
This topic has been discussed in 3 different places: here, the pull request in the roslyn repo, and the sqlite forum post.  It's not clear where to proceed, but I'm going to try here, and tag @Therzok @CyrusNajmabadi @sharwell @AArnott to make sure you all see it.

I believe the central question is around SQLite URIs like this one, which use mode=memory and cache=shared:

```
file:///Users/eric/dev/cb/item407/storage.ide?mode=memory&cache=shared'
```
In such cases, what does the path portion of the URI mean?  I *think* the confusion here is that the path portion is not a path, but rather, a name.

DRH responded in the sqlite forum post with:

> The "mode=memory" flag means to open the database as an in-memory database only, never reading or writing from disk. This is the same as opening the magic ":memory:" database, except that now the database has a name used internally so that multiple in-memory databases can share the same cache and hence see the same data.

> Trying to open an on-disk database using "mode=memory" doesn't make sense.

Andrew, in that forum thread, you argued:

> On the contrary, this is a documented technique that allows multiple sqlite connections...

and you cited a documentation snippet which said:

> the mode=memory query parameter can be used with a URI filename to create a named in-memory database

and which used the following URI as an example:

```
file:memdb1?mode=memory&cache=shared
```
And you finished with:

> So you see we're allowed to combine a file URI with mode=memory. And it works as documented on Windows. Why doesn't it work on mac?

The SQLite docs obviously do say that a file URI can be used with mode=memory, and DRH did not say otherwise, but the docs also say that such a URI is not interacting with an on-disk file.  

From https://www.sqlite.org/uri.html :
> The mode query parameter determines if the new database is opened read-only, read-write, read-write and created if it does not exist, or that the database is a pure in-memory database that never interacts with disk, respectively.

The docs could be clearer, but the implication I see is that when mode=memory is present, the path portion of the URI is not a path, but rather, a name.

Andrew, are you expecting the following URI to use an in-memory database AND to interact with the on-disk database storage.ide?  If so, how are you expecting that to work?

```
file:///path/to/storage.ide?mode=memory&cache=shared'
```

A big confusion here is around the fact that SQLite handles this case a bit differently on Windows vs Unixen.  I am not exactly sure why.  My conjecture is that on Windows, the path portion of the URI is still being treated as a name, even though the contents of that name happen to contain slashes and resemble a path.  And for some reason, on Unix, the code is fussier, notices that the name looks like a path, and behaves differently.

As far as I can tell, the SQLite docs do not say what the rules are for a valid name in the path portion of a file URI which includes mode=memory, but I daresay that using a name which resembles a path makes the URI appear to be doing things it is not.

**Comment by AArnott** [comment]
> are you expecting the following URI to use an in-memory database AND to interact with the on-disk database storage.ide?

No. 
I understand that it's just a name to keep multiple in-memory databases distinct. That's exactly why we use it. 
Our model is that each db on disk gets an in-memory cache that we maintain, so it makes it very simple to simple use the path of the file on disk as the "name" for the in-memory db as well. It works perfectly on Windows. The docs only say it is a URI, so presumably any URI should work. If only certain URI patterns are supported, that should be documented.

> for some reason, on Unix, the code is fussier, notices that the name looks like a path, and behaves differently.

Maybe. If so, I imagine we could hash the path and web64 encode it for the name in order to avoid bothering unix. I don't have a repro of the problem myself. Perhaps @CyrusNajmabadi or anyone else who has one can try substituting any other simpler name for the URI here to see if it works.

**Comment by ericsink** [comment]
Closing, not related to SQLitePCLRaw.

**Comment by wzchua** [comment]
Is CONFIG_URI enabled? I believe i hit something similar 
Calling `raw.sqlite3_config(raw.SQLITE_CONFIG_URI, 1)` fixed my issues

**Comment by AArnott** [comment]
Thank you for sharing, @wzchua. I don't have a mac to try this on, but I am delighted to learn that I can get Mac to behave like Windows simply by setting this configuration option.
