### ISSUE TITLE
thread safe?  raw.sqlite3_prepare_v2(db, sql, out command);

### ISSUE THREAD

**Issue by brettharrisonzya** [ericsink/SQLitePCL.raw#45]
I am using a package(Couchbase Lite .net) that uses SQLitePCL.  I often get hangs on a call to  raw.sqlite3_prepare_v2(db, sql, out command); where this function does not return.  I think I narrowed it down to this Dictionary in sqlite3 not being thread safe.

Should I expect this to be thread safe?  Should the package be making calls to SQLitePCL in a single thread only?

    public class sqlite3 : IDisposable
    {
        private readonly IntPtr _p;
        private bool _disposed = false;
        private Dictionary<IntPtr, sqlite3_stmt> _stmts = new Dictionary<IntPtr, sqlite3_stmt>();  // thread safe??

**Comment by ericsink** [comment]
A sqlite3 connection object is not thread safe.  

You can have multiple threads if you have multiple sqlite3 connections and each one gets its own thread.  This is generally the way sqlite itself works when used from C as well.

In other words, I could make that dictionary thread safe, but there wouldn't be much point, since the underlying native connection handle isn't thread safe either.

**Comment by brettharrisonzya** [comment]
The authors of the couchbase lite package are opening the database (sqlite3_open_v2) with the SQLITE_OPEN_FULLMUTEX flag.  I assume they thought that would allow them to use an sqlite3 connection from multiple threads.  

Is that wrong? 

I see the library creates sqlite3_stmt's in one thread and then uses them in another.  I assume that is the problem if sqlite3 connections are not thread safe.

**Comment by ericsink** [comment]
Hmmph.  I'll need to investigate this further.

FYI to @zgramana

E

**Comment by zgramana** [comment]
FULL_MUTEX == SERIALIZED == thread safe.

The reason it's called FULL_MUTEX is because internally they manage all the locking. Statements own the connection while they execute. I can't recall what the minimum required version of SQLite is though.

**Comment by zgramana** [comment]
THREADED mode works as @ericsink describes.

**Comment by zgramana** [comment]
And we found the same issue with the Dictionary, but thought we submitted a PR with the fix. Perhaps @borrrden can elaborate.

**Comment by borrrden** [comment]
I honestly don't remember the details of that, just that we guard against a race condition when closing statements returned by "next_stmt".  As far as the hang in question this seems relevant:  https://github.com/couchbase/couchbase-lite-net/issues/314 however, these locks have all been removed (but the latest nuget release still has them) in favor of a single thread queuing strategy.  If you have a test which can reliably produce this behavior then bring it over to the Couchbase Lite repo and I'll have a look at it.

**Comment by ericsink** [comment]
Well at the moment I definitely don't have support for FULL_MUTEX, even if the underlying SQLite library was compiled that way.  I would be surprised if that Dictionary is the only issue.  I'll try to write some test cases and get this fixed as soon as I can.

**Comment by brettharrisonzya** [comment]
I don't have time to create a couchbase lite test case this week that reproduces the issue, but I can describe what I'm seeing.

All of the requests to sqlite3 go through the SingleThreadScheduler.  But some of those threads return a Cursor object (which contains a sqlite3_stmt).  That Cursor is used in another thread and eventually Disposed outside of the SingleThreadScheduler.  At that time sqlite3_stmt.Dispose is called which causes the SQLitePCL.raw library to eventually call remove_stmt which Removes an entry from the _stmts Dictionary.

If at the same time the SingleThreadScheduler executes a prepare (though the ugly interface) or directly calling by calling sqlite3_prepare_v2 this will invoke add_stmt in SQLitePCL.raw which also accesses the _stmt Dictionary.  Often this seems to lead to a hang (on iOS).

**Comment by borrrden** [comment]
Interesting to hear!  Actually the DB logic is going to be subject to a massive refactor in the coming days to support ForestDB, so I may clean things up so that this logic goes through the single thread scheduler as well.  Will need to investigate first.

**Comment by ericsink** [comment]
(I gotta stop dragging my feet and get this resolved.)

It sounds like I probably need to get a lock around access to that dictionary.

It also sounds like this lock might be "necessary but not sufficient".  Or maybe "appropriate but not sufficient".  The underlying sqlite library may or may not be capable of FULL_MUTEX.

And the single thread queueing strategy that you couchbase folks are using sounds like you're solving the problem at a higher layer by assuming that the sqlite3 object (and everything below it) may or may not be thread safe.

So anyway, assuming that it is safe for me to add a lock around that dictionary (which may not be a correct assumption -- still need to test that), then I am adding the lock not to solve the threading problem, but simply so that SQLitePCL.raw can stop contributing to the problem.

Thoughts on this?

Thanks.

**Comment by brettharrisonzya** [comment]
I created a pull request for couchbase lite to protect the Dictionary as a work around.
https://github.com/couchbase/couchbase-lite-net/pull/413
