### ISSUE TITLE
SqlitePCL.raw 0.8.0 on nuget doesn't seem to work with Android

### ISSUE THREAD

**Issue by ghost** [ericsink/SQLitePCL.raw#46]
When I include the nuget package into my Android project, it is putting a bait and switch dll in the android references instead, which of course will not run. If I look in the packages folder, all the other libs seem to have a SQLitePCL.raw.dll file in, however, the monodroid folder has a single file called _._ which is zero bytes.

I have tried with both SQLitePCL.raw and SQLitePCL.raw_basic packages and both seem broken.

**Comment by ericsink** [comment]
Usually this error is caused by adding the nuget package to a library
project but not adding it to the actual application project as well.  It
needs to be specifically added in both places.

Any chance that could be the problem here?

E

**Comment by mikeyj2009** [comment]
I am using Akavache in a Xamarin.forms project within Xamarin Studio, the issue is happening when I import SQLitePCL into the Android application project, I have tried just creating an Android application and it did the same thing, could it be the latest version on nuget in Xamarin Studio picking the wrong dll from the project? I had wondered if nuget was picking the wrong dll, so went looking the dll in the packages folder, but couldn't find on for Android so thought the packaging of the nuget file might have been at fault.

The iOS version works perfectly, and I have tried different scenarios of having the SQLitePCL added to the PCL library and removed from the library, but it has made no difference.

**Comment by ericsink** [comment]
It's possible you've found a problem here.  I'll see if I can reproduce it.

But it just seems likely that if 0.8.0 were so very broken on Android, I would have heard about it before now.

Tagging @paulcbetts because it seems likely that if SQLitePCL.raw 0.8.0 completely fails to work with Akavache on Android, he would know.  Or want to know.

BTW, I can confirm that the _._ file you're seeing in that Android lib directory is correct.  On Android, the assembly gets pulled from the build directory, not from the lib directory.  A .targets file controls this.

**Comment by ericsink** [comment]
I just tried running my test suite on Android and everything is working fine for me.  Let's see if we can figure out what is different on your side.  Can you give me as much detail as possible about your configuration and the steps you are following?

Thanks.

**Comment by mikeyjones** [comment]
Eric,

I agree, that I would have thought the error would have cropped up before, so found it strange that my Mac's are being funny, your comment about the target file, lead me to the solution. 

It seems if you add SqlitePCL.raw to a PCL project first, and then to an Android project, it might not add the target in the android proj file, if this fails, xbuild uses the PCL dll, which of course fails. I manual added it to my project and verything started working.

Frustratingly, I have tried to replicated this in a couple of throw away projects, and every time it works as it should, so it must have been messing with me. I swear I tried everything I could think of on the Friday, removing the nugets, clearing builds and even creating a new project within the solution, but nothing seemed to work. at the time.

So I own you an apology, and beer, if we ever meet. Thank you so much for looking into this so fast.

**Comment by ericsink** [comment]
No worries.  Glad it's working for you.  :-)

**Comment by JeffScanco** [comment]
I found the same issue and it seems to be because the lib\MonoAndroid folder does not contain the SQLitePCL.raw.dll like the other lib folders do.  In my project when using the 0.7.1 version, the reference was ..\packages\SQLitePCL.raw_basic.0.7.1\lib\MonoAndroid\SQLitePCL.raw.dll, and after upgrading to 0.8.0: it was ..\packages\SQLitePCL.raw_basic.0.8.0\lib\portable-net45+netcore45+wp8+MonoAndroid10+MonoTouch10+Xamarin.iOS10\SQLitePCL.raw.dll and I see the warning about the bait dll being used.
I need to use the latest Couchbase Lite 1.1.0.1 that requires SQLitePCL.raw (>= 0.8.0), so this issue needs to be resolved
I'm on a Mac using Xamarin Studio, if it helps.   However, I created a brand new project in Visual Studio 2013 and added the package and the MonoAndroid folder was empty there too.

**Comment by ericsink** [comment]
Sorry for terse reply:

The DLLs moved in 0.8 to allow more configs.

I suspect tooling is getting confused in update cases.  IIRC I may have
tested 0.8 only with newly created projects.

Maybe try removing the pkg entirely and re add.

I am traveling with very limited network access. Back in the office next
week.

E

**Comment by mikeyjones** [comment]
Jeff, 

As Eric said, it seems to be an issue with upgrading to the latest version, there should be a msbuild script that gets adding to the csproj file, and it seems to not get adding, a quick (but not ideal fix) is to add a reference to {projroot}packages/SQLitePCL.raw.basic.0.8.0/build/MonoAndroid/pinvoke_sqlite3/anycpu/SQLitePCL.raw.dll. 

I cannot get to the project I was using at the moment, but when I can I'll send the line you need to manually insert into the Android csproj file.

I couldn't get another project to not include the msbuild when I tried, but I know once the project didn't get the msbuild command, it refused to, even when I deleted and re-added the nuget package.

**Comment by JeffScanco** [comment]
Thank you Eric and mikeyjones for you quick replies.
I'm a newbie at how all of this works, so I could look back at what had worked until the upgrade.  I had removed all package references completely, saved the project and closed Xamarin Studio.  I re-opend the project, added the reference to couchbase lite and it added the dependencies for the SQLitePCL raw and ugly.  When that didn't work, I removed everything again, restarted the Studio, and manually added each package with neget.  Same issue.
I manually copied the SQLitePCL.raw.dll from the suggested location from mikeyjones into the lib/MonoAndroid folder and made sure the project referenced it from there (the same location that worked for the 0.7.1 build) and the everything works with 0.8.0.  I do not know if the  pinvoke_sqlite3/anycpu/SQLitePCL.raw.dll is not the correct file to use, but it is working for me as now.
Thanks for pointing me in that direction.

**Comment by mikeyjones** [comment]
Like I said, its a quick but incorrect fix, but at least it allows you to build and run the project. I've had a quick look and found the line you should add to the Android csproj file.

1. If you remove the reference to the SQLitePCL.dll you just added

2. in Xamarin Studio, right click on the android project and select unload, 

3. right click on the unloaded project and goto Tools/Edit File, this brings up the csproj,

4. goto the end of the of the file somewhere before the </Project> tag (You probably will see a few <Import Project..." tags if you do paste the line at the end of these), paste the following into the the file:

<Import Project="..\packages\SQLitePCL.raw_basic.0.8.0\build\MonoAndroid\SQLitePCL.raw_basic.targets" Condition="Exists('..\packages\SQLitePCL.raw_basic.0.8.0\build\MonoAndroid\SQLitePCL.raw_basic.targets')" /> 

Make sure the path is correct to the packages folder from where the csproj file is.

5. right click on the unloaded project and click "Reload" it should now build ok and be selected the correct dll for you.

**Comment by JeffScanco** [comment]
mikey,
I already had that line in my project.  When I remove the line:
    <Reference Include="SQLitePCL.raw">
      <HintPath>..\packages\SQLitePCL.raw_basic.0.8.0\lib\MonoAndroid\SQLitePCL.raw.dll</HintPath>
    </Reference>
from the csproj, the build fails because it cannot fine the SQLitePCL.raw.dll
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'SQLitePCL.raw, Version=0.8.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'SQLitePCL.raw.dll'
  at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) [0x00000] in <filename unknown>:0 
  at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference) [0x00000] in <filename unknown>:0 
  at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences (ICollection`1 assemblies, Mono.Cecil.AssemblyDefinition assembly, Boolean topLevel) [0x00000] in <filename unknown>:0 
  at Xamarin.Android.Tasks.ResolveAssemblies.Execute () [0x00000] in <filename unknown>:0  (ScancoService.Droid)
Running debug works, but I cannot compile because it doesn't find the SQLitePCL.raw.dll.  I've added the MSBuild directive <UseSQLiteFrom>packaged\_sqlite3</UseSQLiteFrom> to bot the debug and release sections thinking that it failed to without a directive, but the targets file should be taking care of that anyways.
I'm thinking that there is an issue with Xamarin Studio using the targets file because it works for another developer using Visual Studio on a pc.

**Comment by ericsink** [comment]
Which version of Xamarin are you using when experiencing this problem?

**Comment by JeffScanco** [comment]
=== Xamarin Studio ===

Version 5.9.3 (build 1)
Installation UUID: a88a45c5-d516-45a4-a1fb-f197ca0a2958
Runtime:
Mono 4.0.1 ((detached/ed1d3ec)
GTK+ 2.24.23 (Raleigh theme)

Package version: 400010044

=== Xamarin.Android ===

Version: 5.1.3.1 (Business Edition)
Android SDK: /Users/TechMac6/Library/Developer/Xamarin/android-sdk-mac_x86
Supported Android versions:
2.3    (API level 10)
4.0.3  (API level 15)
4.1    (API level 16)
4.2    (API level 17)
4.3    (API level 18)
4.4    (API level 19)
4.4.87 (API level 20)
5.0    (API level 21)
Java SDK: /usr
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

=== Xamarin Android Player ===

Not Installed

=== Apple Developer Tools ===

Xcode 6.3.2 (7718)
Build 6D2105

=== Xamarin.iOS ===

Version: 8.10.1.74 (Business Edition)
Hash: 6916d0e
Branch: master
Build date: 2015-06-18 17:18:10-0400

=== Xamarin.Mac ===

Not Installed

=== Build Information ===

Release ID: 509030001
Git revision: 5a524e1726ed103fdd4fe37e0356f2b35466ce9d
Build date: 2015-06-02 16:35:08-04
Xamarin addins: 51957cfbd06be911b212671ad05c2c6221ac90f9

=== Operating System ===

Mac OS X 10.10.3
Darwin Jeffs-iMac-2.local 14.3.0 Darwin Kernel Version 14.3.0
    Mon Mar 23 11:59:05 PDT 2015
    root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

To get around the issue, I've copied the SQLitePCL.raw.dll from the packages/SQLitePCL.raw_basic.0.8.0/build/MonoAndroid/pinvoke_packaged_sqlite3 folder and then added a reference to packages/SQLitePCL.raw_basic.0.8.0/lib/MonoAndroid/SQLitePCL.raw.dll directly.  It seemed that the .targets file would be doing this with the proper MSBuild compiler directive.  I do not know why it does not follow the .targets file direction of importing the dll, but this worked as a work around for me.

Thank You,

Jeffery Partridge
330-645-9959 x106

[cid:39A9BDE6-A8A0-41E5-AE1C-C047158FD345]

Scanco Shipping Address: 1000 Tamiami Trl N
Suite 201
Nokomis, FL 34275

**Comment by ericsink** [comment]
Anyone still experiencing problems here might want to review the discussion of issue #48 and see if Microsoft.Bcl.Build.targets is in play.

**Comment by dhaligas** [comment]
@ericsink please fix this .. the BCL is getting in my way as well .. I have to downgrade back to 0.7.1

**Comment by ericsink** [comment]
Shoot.  I keep forgetting to experiment with the proposed workaround that somebody suggested over in the iOS version of this issue.

Thanks for the nag.

**Comment by jcmm33** [comment]
Just to chime in, but we've just seen this as well when we upgraded our Android solution to the latest version. For now we've just linked directly to the android assembly file.

**Comment by ericsink** [comment]
Nuget package 0.8.3-pre1 contains an experimental fix suggested by @PureWeen

**Comment by ericsink** [comment]
By chance has anybody had an opportunity to see if 0.8.3-pre1 helps?

**Comment by PureWeen** [comment]
Seems to work.... I upgraded all my projects to 0.8.3-pre1 and the iOS project ran without any issues... 

With the previous version I would have had to go in and mess with the targets

**Comment by jcmm33** [comment]
Just tried it this morning with an Android solution that previously didn't work without manual adjustment of the references. It appears to have worked fine.

**Comment by ericsink** [comment]
0.8.3 is on nuget and contains the workaround from @PureWeen

**Comment by eoinahern** [comment]
having some issues with this myself. getting a linkassemblies failed unexpectedly error. removed akavache, splat and rx but i still seem to be getting the same issue.

**Comment by ericsink** [comment]
@eoinahern Please open a new issue, and include lots of details.  What versions of the package(s) are you using?  What error messages are you seeing?  etc.
