### ISSUE TITLE
Figure out possible problem with sqlite3mc and the heap_limit functions

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#564]
During #563 there was a problem with the test cases involving heap_limit.  These tests have been temporarily disabled, but need to be brought back.

**Comment by ericsink** [comment]
cc/ @utelle

**Comment by ericsink** [comment]
FWIW, I get the same error when running the test suite in my local dev environment, on a Mac.

**Comment by ericsink** [comment]
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.12]     SQLitePCL.Tests.test_cases.test_sqlite3_soft_heap_limit64 [FAIL]
  Failed SQLitePCL.Tests.test_cases.test_sqlite3_soft_heap_limit64 [11 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 20971520
Actual:   10485760
```

**Comment by utelle** [comment]
> ```
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.
> [xUnit.net 00:00:01.12]     SQLitePCL.Tests.test_cases.test_sqlite3_soft_heap_limit64 [FAIL]
>   Failed SQLitePCL.Tests.test_cases.test_sqlite3_soft_heap_limit64 [11 ms]
>   Error Message:
>    Assert.Equal() Failure
> Expected: 20971520
> Actual:   10485760
> ```

I inspected SQLite's code and the test code.

SQLite has a data structure which holds the soft and the hard heap limit. Both values are initialized to **0**, unless the symbol `SQLITE_MAX_MEMORY is defined with a different value at compile time. As far as I can tell, the `cb` repo doesn't set this symbol.

That is, SQLite starts with soft and hard heap limit equal **0**.

However, obviously the first call to `sqlite3_soft_heap_limit64()` returns the value **10485760**. Otherwise it could not request a new limit of **20971520**. How can the _soft heap limit_ be already **10485760**, although `sqlite3_soft_heap_limit64()` was not called anywhere else before the _soft heap limit test_ started (or did I miss a call to`sqlite3_soft_heap_limit64()`)?

So, if `sqlite3_soft_heap_limit64()` was **not** called elsewhere, something else must have happened, before `sqlite3_soft_heap_limit64()` was called for the first time. What could that be? (I will give the answer in a minute.)

Another question is, under which circumstances can it happen, that `sqlite3_soft_heap_limit64()` does **not** set the _**requested** soft heap limit_. Inspecting the code of `sqlite3_soft_heap_limit64()` reveals that this can only happen, if the _hard heap limit_ has a value > 0 and is smaller than the requested _soft heap limit_. In that case the _soft heap limit_ is set to the same value as the _hard heap limit_.

Now, how can the _hard heap limit_ have the value of **10485760**? This has to be the case. Otherwise you would not get this value back on querying for the actual _soft heap limit_ value on the first call.

The answer can only be that the _hard heap limit test_ (which is also included in the test suite) ran ** before** the _soft heap limit test_. If this is the case, the result of the _soft heap limit test_ can be explained easily:

When a new _soft heap limit_ of **20971520** is requested, the value is checked against the _hard heap limit_ value (which is **10485760**). Because this value is smaller than the new requested _soft heap limit_, the _soft heap limit_ is set to the value of the _hard heap limit_. And that's why the second query of the _soft heap limit_ returns **10485760** instead of the expected value **20971520**.

My explanation is that the _hard heap limit test_ runs before the _soft heap limit test_, causing the observed results. What I can't explain is, why this happens only for `sqlite3mc` and not `sqlite3` or `sqlcipher`.

However, I'm quite confident that it has nothing to do with `sqlite3mc`, but with the behaviour of the test environment.

**Comment by ericsink** [comment]
Nice detective work.

I tried changing both tests to reset their limits back to 0 after doing their checks.  That seems to fix the problem.

**Comment by utelle** [comment]
Please do the following:

Add this call at the beginning of the test `test_sqlite3_soft_heap_limit64()` before calling `raw.sqlite3_soft_heap_limit64(-1)`:
```cs
var previousHardLimit = raw.sqlite3_hard_heap_limit64(0);
```
This way you should get a clean initial state, and the test should no longer fail.

If possible show the value of `previousHardLimit` in the output.

**Comment by utelle** [comment]
I saw your post only after I submitted my previous one.

> Nice detective work.

My specialty. 😄 

> I tried changing both tests to reset their limits back to 0 after doing their checks. That seems to fix the problem.

I'm not surprised. 😆
