### ISSUE TITLE
Cannot load DLL

### ISSUE THREAD

**Issue by henrylsun** [ericsink/SQLitePCL.raw#67]
Hi there,  

We are using CouachDB Lite which has SQLitePCL as dependency.  Everything works perfectly locally on my development machine (windows 7).  However, when our CI Server (MS Server 2008 box) builds the .net MVC web project and deploy it to our Web Server (MS Server 2012 box), we getting an exception says: 

The type initializer for 'Couchbase.Lite.Store.SqliteCouchStore' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found.

So I downloaded the latest version of 32bits sqlite3.dll from sqlite.org and dropped it into the folder overriding the one generated at build time, everything works...  I don't have much knowledge of PCL libraries but it looks like this might be similar to issue 44?  Just wondering if you could shed some light on how to solve this issue? Would referencing VC++ extension SDK in my project solve this issue? 

Thanks,
Henry

**Comment by henrylsun** [comment]
A stupid quesiton, does SQLitePCL split out the two verions of sqlite3.dll at build time?

**Comment by ericsink** [comment]
(responding to your first question)

What's probably happening here is that your Server 2012 machine does not have the C runtime lib DLL that is expected by the sqlite3.dll.

The one from sqlite.org works because it is statically linked to the C runtime, and because you're on a desktop OS, where such static linking is allowed.

I'm in the process of overhauling the mechanism by which SQLitePCL.raw interacts with the native code, so this is all getting a fresh look as part of that effort.  I should probably just bundle sqlite3.dll's which have the C runtime lib statically linked when possible, since this is such a common case.  I would just have to think through the inconsistency of sometimes having the C runtime statically linked and sometimes not.

**Comment by ericsink** [comment]
(responding to your second question)

Which two versions do you mean?  The 32bit and the 64 bit?

**Comment by henrylsun** [comment]
Ericsink,
Thanks for your prompt reply. Please ignore my second question. I figured it out :).  So for us, before the new version of SQLitePCL is released, I need to stop SQLitePCL from emitting sqlite3.dll and then bundle the one I downloaded in my project?  How do I stop SQLitePCL from creating sqlite3.dll?

**Comment by ericsink** [comment]
Try setting the msbuild property `UseSQLiteFrom` to the value `elsewhere`

I'm not sure if that setting is supported in your situation, but it's the first thing to try.

How this works:

There is a .targets file in the nuget package which is used to copy the sqlite3.dll over to your build directory.  The UseSQLiteFrom property can be used to control whether that copy happens or not.

Anyway, if you don't want that sqlite3.dll copied over, you need to prevent that targets file from doing its thing.

Like I said, this will all be different (read: "better") in 0.9.

**Comment by henrylsun** [comment]
Thank you Eric. Looking forward to the new release!
