### ISSUE TITLE
SQLitePCL.raw_basic obsolescence

### ISSUE THREAD

**Issue by dominik-weber** [ericsink/SQLitePCL.raw#80]
Have you considered updating the raw_basic package so that it no longer contains any assemblies but includes a dependency on the new SQLitePCL.raw package? This way older nuget packages depending on raw_basic and newer packages referencing raw could be used simultaneously without breaking compatibility.

**Comment by ericsink** [comment]
Interesting idea.

I have been very unsure about what to do with raw_basic, as all options have pros and cons.

Since many (most?) of my users are using raw_basic, and since 0.9.x is a breaking change for some (many?) use cases, I figured maybe the best (least bad?) option would be to leave raw_basic back at 0.8.6, because switching to a different package ID does a better job setting expectations for a possibly non-seamless upgrade, and also because it gave me the opportunity to write this really long run-on sentence.

**Comment by dominik-weber** [comment]
Wow, that was quick ;)
Akavache for example still uses the raw_basic package, an update path like explained above would allow me to update to the new 0.9.1 raw package without having to do some nuget trickery to remove the dependency on raw_basic (as the two can't be installed at the same time), while you would't have to keep on updating both packages.

I'm not much into nuget package creation, but isn't there a way you could open a web page explaining the breaking changes when updating the package? I *think* the newtonsoft.json package does something like this...

**Comment by ericsink** [comment]
Hmmm.  Okay, you've still got me thinking about this.

But I should probably also talk to the Akavache people about switching their dependency from SQLitePCL.raw_basic to SQLitePCL.raw.  So I'm tagging @paulcbetts, because either he is the right person or he knows who is.

**Comment by dominik-weber** [comment]
I have actually created an issue regarding this last november: https://github.com/akavache/Akavache/issues/257

**Comment by ericsink** [comment]
Need to migrate Akavache to the 1.0 release
