### ISSUE TITLE
Update to SQLite 3.14.1 (Desktop)

### ISSUE THREAD

**Issue by ps30** [ericsink/SQLitePCL.raw#86]
Just did an update to 0.9.3 and the included SQLite binary is the older 3.12.2 (current version is 3.13.0)

I am running desktop Windows 10 64 bit using .Net 4.5.2 C# WPF application, and with the new packaging style I am confused as to which Nuget package is delivering my sqlite3.dll.  Are all the following auto installed nuget packages required for a Windows .Net 4 desktop application?   Before it was only 2 packages (sqlite-net-pcl & SQlitePCL.native):

package id="sqlite-net-pcl" version="1.1.2" targetFramework="net452" /
package id="SQLitePCL.bundle_green" version="0.9.3" targetFramework="net452" />
package id="SQLitePCL.native.sqlite3.v110_xp" version="0.9.3" targetFramework="net452" />
package id="SQLitePCL.plugin.sqlite3.net45" version="0.9.3" targetFramework="net452" />
package id="SQLitePCL.raw" version="0.9.3" targetFramework="net452" />

Can we get the sqlite3.dll binary updated to 3.13.0 for windows desktop apps, or is it now trying to use the native Microsoft Windows 10 sqlite3.dll?

(Edit: Re-reading the new docs it seems that SQLitePCL.native.sqlite3.v110_xp is the package now delivering sqlite3.dll for desktop - Could this be updated to the latest SQLite 3.10.0?)

**Comment by ericsink** [comment]
Yes, I will be updating the SQLite binaries.  Maybe to 3.13, but 3.14 is imminent.

Yes, the packaging structure for 0.9.x is different.

No, I do not currently support using the built-in SQLite with Windows 10.  It's actually called winsqlite3.dll.

Your note looks like it wanted to include a list of packages but they got mangled.  Anyway, yes, it is likely that you need several packages for your case.

SQLitePCL.raw is the main assembly.

SQLitePCL.native.* contains the native SQLite code, but its name is actually esqlite3.dll (note the 'e'), to eliminate conflicts with situations where there is already a more official 'sqlite3.dll'.

SQLitePCL.plugin.* is the thing that tells the main assembly how to load esqlite3.dll (note the 'e').

SQLitePCL.bundle_green is a meta package that tells sqlite-net-pcl what other packages to load for each platform.  In this case, it sees that you are on net45 and it loads the stuff above, and provides Batteries.Init(), which, in your case, you need to call at app startup somewhere.  The bundle_green package was designed to give a "batteries included" experience specifically for sqlite-net-pcl users.  

FWIW, bundle_green tries to create ease of use by removing flexibility.  In your case, it could have encapsulated other policy choices.  For example, it could skip 'native' and just use the Windows 10 winsqlite3.dll, but the ability to figure that out would require nuget 3.x features, and I haven't made that jump yet due to concerns about compatibility.  Another policy choice would be to skip 'native' and let you provide 'sqlite3.dll' using the SQLite extension SDK.

I hope this helps.

**Comment by ericsink** [comment]
Actually, I forgot -- I think that Batteries.Init() call is actually *in* sqlite-net-pcl, so nevermind that part.

**Comment by ericsink** [comment]
The e_sqlite3 binaries in release 1.0.0 are 3.14.1
