### ISSUE TITLE
Xamarin Cycle 8 (Android) - DllNotFoundException: sqlite3 (version 0.8.6)

### ISSUE THREAD

**Issue by manuelcosta74** [ericsink/SQLitePCL.raw#91]
Hi guys

we are having issues loading sqlite3 library and we also had it with Sqlite-net. To try to re-map it to Xamarin's, we did try to add SQLitePCL.raw.dll.config as

`<configuration>
  <dllmap dll="sqlite3" target="libsqlite3_xamarin.so" />
</configuration>`

This same logic solved sqlite-net, but it not working with SQLitePCL.raw. Any suggestion to have this issue solved?

cheers

**Comment by ericsink** [comment]
To be clear, you are trying to load libsqlite3_xamarin with SQLitePCL.raw?  Version 0.8.6 cannot do that.

In fact, right now, version 0.9 cannot do that either, but this will be supported in the upcoming 0.9.4 release.

That configuration/dllmap syntax is not something I have tested with SQLitePCL.raw, so I assume it will not work.

For now, I cannot suggest a solution other than to work with a different instance of the sqlite3 library (instead of libsqlite3_xamarin.so) and wait for 0.9.4.  The system SQLite on Android is supported unless you are on Android N.  The SQLite bundled with SQLitePCL.raw for Android should work fine as well.  That said, if you are trying to use libsqlite3_xamarin.so, I suspect that means that you are also using Mono.Data.Sqlite, so using multiple native SQLite library instances would expose you to the risk of data file corruption.

**Comment by manuelcosta74** [comment]
Hi Eric

we are using it through Akavache official nuget packages, which means we are using SQLitePCL.raw_basic 0.8.6.
From my understanding of dllmap, it will redirect LibraryPath calls through DllImport(LibraryPath. I'm not completely sure about this either, though.
As for file corruption, do you mean concurrent write operations going through different instances? 
However, i'm confuse why this is happening outside Android N. Shouldn't we have access to libsqlite3.so? This is happening independently of the Android OS version and it is happening as a consequence of the Xamarin SDK update.
Nevertheless, it seems that Android N is creating a nightmare in terms of maintenance!

**Comment by ericsink** [comment]
"As for file corruption, do you mean concurrent write operations going through different instances?"

Yes.  But let's set that aside for now.

You're on Akavache?  That's different.  This should be working.

Let's see if I understand.  Things were working.  Then you did some kind of Xamarin update and things stopped working.  And your attempt to use libsqlite3_xamarin.so was part of your attempt to fix it, not because you specifically wanted to use that instance of sqlite.

Is that right?

**Comment by manuelcosta74** [comment]
"Let's see if I understand. Things were working. Then you did some kind of Xamarin update and things stopped working. And your attempt to use libsqlite3_xamarin.so was part of your attempt to fix it, not because you specifically wanted to use that instance of sqlite."

yes, 100% correct.  Note that also sqlite-net got screwed also and not only Akavache / SQLitePCL.raw. Sqlite-net was solved with dllmap

**Comment by ericsink** [comment]
So the interesting question is why the Xamarin update caused this.  I haven't heard of that before.  Which versions of the Xamarin stuff did you switch from/to?

**Comment by manuelcosta74** [comment]
Taking just Android as a reference we did change from 6.1.2.21 (Stable channel) to 6.2.0.36 (Beta Channel, public version of Cycle 8)

**Comment by ericsink** [comment]
OK.  I'll try to find time to install cycle 8 and see what is going on.

It is also becoming more and more important that I work with the Akavache people to upgrade their SQLitePCL.raw to 0.9.x.

**Comment by manuelcosta74** [comment]
SQLitePCL.raw.dll.config seems to work. This config file is used only if you place it in same folder as dll. What i did was:
go to packages folder and added it to

SQLitePCL.raw_basic.0.8.6/build/MonoAndroid/pinvoke_packaged_sqlcipher/anycpu
SQLitePCL.raw_basic.0.8.6/build/MonoAndroid/pinvoke_packaged_sqlite3/anycpu
SQLitePCL.raw_basic.0.8.6/build/MonoAndroid/pinvoke_sqlite3/anycpu

What i was doing before and that did not work was to have SQLitePCL.raw.dll.config being copied to the output folder of the project producing an apk

Now why DllImport("sqlite3" is not able to arrive to sqlite native library... have no idea.

**Comment by ericsink** [comment]
That's good to know.  Thanks.
